### ISSUE TITLE
misleading text in scp ui

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#100]
For the type of button such as the one with the popup in the image below, the text before the check box says "Use no data" but the pop up text says "ignore no data". This seems to be misleading and a bit confuse. Maybe it could be clarified. This text is used for many tools. 
![USE OR IGNORE NO DATA](https://user-images.githubusercontent.com/44610746/78080024-a56ad580-73ad-11ea-854b-8506ae2b0664.PNG)

**Comment by semiautomaticgit** [comment]
It should be updated in the new version 7.
If you still get the same issue, please reopen it
