### ISSUE TITLE
Download products "unable to connect"

### ISSUE THREAD

**Issue by GSavelev-VSEGEI** [semiautomaticgit/SemiAutomaticClassificationPlugin#103]
After second preview adding (sometimes after the first) preview temporary layer adding to the project the search works (it is possible to make requests) but preview doesn't

![image](https://user-images.githubusercontent.com/57714410/79380462-2c50ae00-7f69-11ea-9aa8-394d657a93bc.png)

**Comment by GSavelev-VSEGEI** [comment]
The problemm semmed to be with the server: I tried to download the landsat images from earth explorer - didn't work either.

In couple hours everything worked

**Comment by semiautomaticgit** [comment]
Thank you for your feedback
