### ISSUE TITLE
landsat data download issue

### ISSUE THREAD

**Issue by AQuddoos** [semiautomaticgit/SemiAutomaticClassificationPlugin#106]
An error has occurred while executing Python code: 

AttributeError: 'module' object has no attribute 'SSLContext' 
Traceback (most recent call last):
  File "C:/Users/Abdul Quddoos/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\downloadlandsatimages.py", line 155, in findImages
    self.downloadMetadata()
  File "C:/Users/Abdul Quddoos/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\downloadlandsatimages.py", line 204, in downloadMetadata
    searchResult = cfg.utls.NASASearch(searchUrl)
  File "C:/Users/Abdul Quddoos/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 321, in NASASearch
    newContext = cfg.sslSCP.SSLContext(cfg.sslSCP.PROTOCOL_TLSv1_2)
AttributeError: 'module' object has no attribute 'SSLContext'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, ff83b9a479 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/Abdul Quddoos/.qgis2/python
C:/Users/Abdul Quddoos/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Abdul Quddoos/.qgis2//python

**Comment by semiautomaticgit** [comment]
Hello.
The error is related to an old unsupported version of the plugin.
Please update to the latest version of QGIS and SCP.

**Comment by AQuddoos** [comment]
Hello Sir!
I am doing correction on SCP and calculate lst on GIS with manual method
and then both correction and calculate lst manual the results are not same.
Manual results are may be most match to reality but correction through SCP
results are sooo high that are not match. Please guide me about this.
Thanks.
