### ISSUE TITLE
HTTP 401 for fresh copernicus account

### ISSUE THREAD

**Issue by nilsnolde** [semiautomaticgit/SemiAutomaticClassificationPlugin#107]
I wanted to download data and it's throwing a 401, Unauthorized. I tried to access the [URL](https://scihub.copernicus.eu/apihub/search?q=S2*%20AND%20cloudcoverpercentage:[0%20TO%20100]%20AND%20beginPosition:[2020-05-10T00:00:00.000Z%20TO%202020-05-14T23:59:59.999Z]%20AND%20footprint:"Intersects(POLYGON((9.9034151916607%2051.199013063096,9.9034151916607%2051.195257520784,9.9116276676279%2051.195257520784,9.9116276676279%2051.199013063096,9.9034151916607%2051.199013063096)))"&rows=20&start=0) the plugin is calling manually, which prompts for the Basic auth and also there I can't login. However, with the same credentials I can login to https://scihub.copernicus.eu/dhus/#/home.

I realize this is not a plugin issue. If you could let me know the proper address I'll gladly report it there. And leave it here in case other people experience the same.

**Comment by semiautomaticgit** [comment]
Hello, it is not a plugin issue, but the way the service works.
At the moment I can't find the link, but it is described on the the Copernicus service https://scihub.copernicus.eu/ .

**Comment by nilsnolde** [comment]
Thanks @semiautomaticgit, found it:
https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription

> The same user credentials are made valid to access this site within 1 week from the registration on SciHub.

haha what? never heard of anything like that.

**Comment by semiautomaticgit** [comment]
Yes, you found it. 
Usually it takes a couple of days.

Cheers
