### ISSUE TITLE
FloatingPointError: invalid value encountered in greater_equal 

### ISSUE THREAD

**Issue by smdiazl** [semiautomaticgit/SemiAutomaticClassificationPlugin#108]
Ha ocurrido un error mientras se ejecutaba el código de Python: 

FloatingPointError: invalid value encountered in greater_equal 
Traceback (most recent call last):
  File "C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\dock\scpdock.py", line 2511, in saveROItoShapefile
    cfg.utls.calculateSignature(cfg.shpLay, cfg.bandSetsList[cfg.bndSetNumber][8], [self.ROILastID], cfg.ROIMacroID, cfg.ROIMacroClassInfo, cfg.ROIID, cfg.ROIInfo, 50, 40, "No", "No", UID)
  File "C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 1754, in calculateSignature
    ROIsize = cfg.utls.getROISize(bX, 1, rStat[0], rStat[1])
  File "C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 5722, in getROISize
    s = ( (a >= min) & (a FloatingPointError: invalid value encountered in greater_equal

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.8.3-Zanzibar Zanzibar, 685d8b15d2 

Ruta de Python:
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\qgis-otb-plugin
C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Sandra Diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs

[log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4657743/log.txt)

![Error](https://user-images.githubusercontent.com/65670312/82464965-4f004600-9a84-11ea-8879-0cfc8fa40750.png)

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
