### ISSUE TITLE
Sentinel 2 data older than 2019 not online (Basic Tutorial 2)

### ISSUE THREAD

**Issue by freimer453** [semiautomaticgit/SemiAutomaticClassificationPlugin#109]
Hello, thanks for the great tool. I verified also on Sci Hub GUI that all S2 files older than 2019 are OFFLINE. Attempts to request to restoration online not yet successful.

This affects data used for Basic Tutorial 2.

**Comment by semiautomaticgit** [comment]
Thank you for your feedback.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version of the manual
