### ISSUE TITLE
QGIS error 40 & SCP plugin error SSL certificate failure?

### ISSUE THREAD

**Issue by cdeforesta** [semiautomaticgit/SemiAutomaticClassificationPlugin#111]
Hi everyone,

I’m having issues downloading satellite images using the SCP plug-in for QGIS. The satillite images appear in the product list but i cant display a preview image or download the products. I get ‘error 40 – Unable to connect’. I have also added the debug log file, so you guys can have a look. The developer of SCP said "it is an installation issue related to the Python version and SSL certificates. You could try to update the Python version." But i'm not really sure what i'm supposed to do.

P.S i have already reinstalled QGIS multiple times and i’m pretty sure i installed GDAL,OGR,Numpy,SciPy and Matplotlib using Homebrew. (still very new to all of this)

I'll gladly take any help i can get!

Thanks,

Charles

[SCP_error_log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4823774/SCP_error_log.txt)
![QGIS error message](https://user-images.githubusercontent.com/63056299/85514857-c3d31c80-b5fc-11ea-9b0b-bb6a108bbef8.png)

**Comment by semiautomaticgit** [comment]
Hello, I confirm you should upgrade the Python version.
You could try this command in the terminal
`pip3 install certifi --upgrade`

**Comment by cdeforesta** [comment]
Hi Luca,

I just tried the terminal command you sent me. this was the response i received: 

Charless-MacBook-Pro-2:~ Charles$ pip3 install certifi --upgrade
Requirement already up-to-date: certifi in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (2020.6.20)
Charless-MacBook-Pro-2:~ Charles$ 

Kind regards,

Charles

**Comment by semiautomaticgit** [comment]
Hi Charles,
possibly this can help https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore

**Comment by cdeforesta** [comment]
Thank you Luca, i will give it a go and let you know.

Kind regards,

Charles

**Comment by dvdbisong** [comment]
I am having exactly the same issues. @cdeforesta were you able to solve this?
I get the same error with QGIS on MacOS Catalina.

**Comment by semiautomaticgit** [comment]
I'm closing this because it is related to the version 6 of SCP.
However, this is still an issue in version 7, so please continue this post here https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/135
