### ISSUE TITLE
Error [38]: unable to load raster 

### ISSUE THREAD

**Issue by mina91dandelion** [semiautomaticgit/SemiAutomaticClassificationPlugin#112]
Hello, I can't load the raster images after I apply pre-processing in SCP. It seems the process works fine until the end, when the raster cannot be loaded. Thank you.

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
