### ISSUE TITLE
Problem during Preprocessing

### ISSUE THREAD

**Issue by santaclausa** [semiautomaticgit/SemiAutomaticClassificationPlugin#116]
Hello everyone

When I try to run the Preprocessing function (Landsat) it only loads until 90% and returns the following error:

File "/Users/me/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 2394, in createVirtualRaster
              gt = gdalRaster.GetGeoTransform()
             AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'

Any ideas how to resolve my problem?

Thank you in advance!

**Comment by semiautomaticgit** [comment]
Hello, probably it is an issue related to QGIS installation, please read this https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
