### ISSUE TITLE
Problem with cloud masking

### ISSUE THREAD

**Issue by Almeida100** [semiautomaticgit/SemiAutomaticClassificationPlugin#117]
Cloud masking stops with several error messages. Error messages attached.
[Provlem with cloud masking.zip](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5249908/Provlem.with.cloud.masking.zip)

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
