### ISSUE TITLE
Python error using ROI Pointer

### ISSUE THREAD

**Issue by mudomau** [semiautomaticgit/SemiAutomaticClassificationPlugin#118]
I just updated to the latest version of SACP, and now whenever I try to use it I get all sorts of python errors.

This is what I get when using the ROI pointer to try to create a ROI:

![imagen](https://user-images.githubusercontent.com/2564029/93981870-cf132100-fd80-11ea-9285-7559866b7d6d.png)

This is using the latest version of QGIS, on a windows 10 machine.

**Comment by mudomau** [comment]
In addition to this, when trying to use the ROI Polygon instead of the ROI Pointer, I get an error saying that the raster could not be read (Bands not propperly aligned). This had never been an issue before.

**Comment by semiautomaticgit** [comment]
Hello, please update QGIS to the latest version.
If you still get this error, please copy the plugin log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
