### ISSUE TITLE
Accuracy assessment

### ISSUE THREAD

**Issue by DanielKovacs96** [semiautomaticgit/SemiAutomaticClassificationPlugin#119]
Hi all users!
Please note that Accuracy assessment in Postprocessing is not working at all with the new version 7 of Semi-Automatic Classification Plugin. Finally I just reinstalled the previous 6 version.
And also, it's a little bit annoying that the menu buttons in the main window don't work.
Hope you will fix it.
![1](https://user-images.githubusercontent.com/73549426/97340765-dc925e00-188c-11eb-9aa5-ddd00476decf.png)

**Comment by semiautomaticgit** [comment]
Hi, thank you for reporting this. 
Please update the plugin, it should be solved now
