### ISSUE TITLE
problem with Semi-Automatic Classification Plugin 

### ISSUE THREAD

**Issue by ljmartinezm** [semiautomaticgit/SemiAutomaticClassificationPlugin#12]
Dear Friends:
I have installed Semi-Automatic Classification Plugin (today with QGIS 2.17) in Windows 64b, when i select the classification algoritm the following error appear: 

2016-09-08T09:27:31	1	Traceback (most recent call last):
			  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\classificationdock\classificationdock.py", line 53, in algorithmName
			    cfg.algName = str(cfg.uidc.algorithm_combo.currentText())
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)

**Comment by ljmartinezm** [comment]
I am working with sentinel2 images

**Comment by ljmartinezm** [comment]
Ha ocurrido un error mientras se ejecutaba el código de Python: 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\classificationdock\classificationdock.py", line 53, in algorithmName
    cfg.algName = str(cfg.uidc.algorithm_combo.currentText())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)

Versión de Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versión de QGIS: 2.17.0 Master, c2f0fff 
Ruta de Python:
•	C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
•	C:/OSGEO4~1/apps/qgis-dev/./python
•	C:/Users/famar1/.qgis2/python
•	C:/Users/famar1/.qgis2/python/plugins
•	C:/OSGEO4~1/apps/qgis-dev/./python/plugins
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
•	c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
•	C:\OSGEO4~1\apps\orfeotoolbox\python
•	C:\OSGeo4W64\bin
•	C:\OSGEO4~1\bin\python27.zip
•	C:\OSGEO4~1\apps\Python27\DLLs
•	C:\OSGEO4~1\apps\Python27\lib
•	C:\OSGEO4~1\apps\Python27\lib\plat-win
•	C:\OSGEO4~1\apps\Python27\lib\lib-tk
•	C:\OSGEO4~1\bin
•	C:\OSGEO4~1\apps\Python27
•	C:\OSGEO4~1\apps\Python27\lib\site-packages
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\OWSLib-0.7.2-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
•	C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
•	C:/Users/famar1/.qgis2//python
B:/sen2-topcart/S2A_OPER_MSI_L1C_TL_MTI__20160625T214656_A005270_T18NZK_con

**Comment by semiautomaticgit** [comment]
Thank you very much for reporting this issue. I have fixed this in v. 5.0.5.
Please reopen this if you still get the same error after the update

**Comment by ljmartinezm** [comment]
Thank you for your answer.  I reinstall the plugin but still i have version 4

**Comment by ljmartinezm** [comment]
The error still remain

**Comment by ljmartinezm** [comment]
Now is working I copied and replaced the files
Thank you very much for your help
Best regards
Joel

**Comment by ljmartinezm** [comment]
I have another problem with PCA and sentinel 2 images: when I run the PCA appears the error:

Ha ocurrido un error mientras se ejecutaba el código de Python: 

LinAlgError: Eigenvalues did not converge 
Traceback (most recent call last):
  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 46, in calculatePCAAction
    self.calculatePCA()
  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 93, in calculatePCA
    self.PCACalculation(rD, bL, outF, numbComp, None, batch)
  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 133, in PCACalculation
    comp, totalVariance, totalVarianceCumulative, eigenValues = self.calculateEigenVectors(covM)
  File "C:/Users/famar1/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 256, in calculateEigenVectors
    val, vect = cfg.np.linalg.eigh(matrix)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\numpy\linalg\linalg.py", line 1246, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\numpy\linalg\linalg.py", line 96, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
LinAlgError: Eigenvalues did not converge


Versión de Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versión de QGIS: 2.17.0 Master, c2f0fff 

Ruta de Python:
C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/famar1/.qgis2/python
C:/Users/famar1/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\OSGEO4~1\apps\orfeotoolbox\python
C:\OSGeo4W64\bin
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
c:\osgeo4~1\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
c:\osgeo4~1\apps\python27\lib\site-packages\owslib-0.7.2-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\pytz-2012j-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win-amd64.egg
c:\osgeo4~1\apps\python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/famar1/.qgis2//python
B:/sen2-topcart/S2A_OPER_MSI_L1C_TL_MTI__20160625T214656_A005270_T18NZK_con

**Comment by semiautomaticgit** [comment]
Thank you for reporting this. Possibly it is related to the image values.
Could you try with a different image?
