### ISSUE TITLE
NO ACTION WHEN CLICKING ON SCP MENU SCP7 in QGIS3.16

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#120]
In the SCP 7 menu (confer image) sometimes (most of the time) there is no reaction of the interface when clicking on different menu. I click on different menus but the interface is not changing.  In the image I click on "Liste des bandes" but the interface "classification" remains. 
![image](https://user-images.githubusercontent.com/44610746/97474338-4c1b5280-194c-11eb-865b-9783cc9f3847.png)

**Comment by semiautomaticgit** [comment]
Thank you very much, fixed in 7.0.5
