### ISSUE TITLE
Default nodata value MODIS preprocessing is -999

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#124]
Default nodata value MODIS preprocessing is -999 while it is 0 for all other sensors and also for  modis in the documentation. It should maybe be harmonized. 

![image](https://user-images.githubusercontent.com/44610746/97551614-7cf29a80-19d3-11eb-848d-d8fbd2d585dd.png)

![image](https://user-images.githubusercontent.com/44610746/97551654-88de5c80-19d3-11eb-93e4-e40b1ec25939.png)

**Comment by semiautomaticgit** [comment]
Thank you. Actually the correct value is -999 so I'm correcting the user manual
