### ISSUE TITLE
Very Simple Student Issue

### ISSUE THREAD

**Issue by CalvinStudent** [semiautomaticgit/SemiAutomaticClassificationPlugin#126]
Hello, I am only in the beginning of using this plugin as I am getting into remote sensing at school and I am having some issues running the band set tool on my mac. When I attempt to run the tool with all my layers in place, an endless stream of new QGIS tabs starts to open and there is no new layer. I'm sorry if this is a very barebones way of describing the issue I just do not have much experience with these tools. Thanks

**Comment by semiautomaticgit** [comment]
Hello, it seems an installation issue.
Please read these instructions https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac

**Comment by semiautomaticgit** [comment]
I'm closing this because I think it is the same issue reported here https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/144 , so please continue posting there
