### ISSUE TITLE
ERROR exception: module 'sys' has no attribute 'argv'

### ISSUE THREAD

**Issue by Almeida100** [semiautomaticgit/SemiAutomaticClassificationPlugin#127]
Please have a look to the attached file.
This file has the results of clicking on Test Dependencies button in "Settings -> Debug".
Many thanks
[Dependencies tested.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5470546/Dependencies.tested.txt)

**Comment by semiautomaticgit** [comment]
Hello, it seems an installation issue. Please try to install QGIS again

**Comment by semiautomaticgit** [comment]
Please reopen if it is stil an issue
