### ISSUE TITLE
Not able to do pre-processing 

### ISSUE THREAD

**Issue by rahulkgour** [semiautomaticgit/SemiAutomaticClassificationPlugin#128]
A couple of issues, not sure related to each other, So mentioning both over here, I using QGIS on Mac OS.

1. While pre-processing Sentinal 2 data in QGIS version 3.10 and 3.14, QGIS getting crashed.

2. Getting below error while starting up QGIS, it's happening every single time when firing up the QGIS.

**Couldn't load plugin 'sentinel2_download' due to an error when calling its classFactory() method**

**ModuleNotFoundError: No module named 'ee_plugin'**
Traceback (most recent call last):
File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
plugins[packageName] = package.classFactory(iface)
File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/init.py", line 12, in classFactory
from .Sentinel2_Download_Menu import s2_menu
File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Menu.py", line 4, in
from .Sentinel2_Download_Dialog import *
File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Dialog.py", line 6, in
from .Sentinel2_Download_Library import *
File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Library.py", line 7, in
from ee_plugin import Map
File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee_plugin'

Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
QGIS version: 3.10.11-A Coruña A Coruña, d217117

Python Path:
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.10.app/Contents/Resources/python
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor

**Comment by semiautomaticgit** [comment]
Hello,

the error you are reporting is related to a different plugin 'sentinel2_download'.

**Comment by rahulkgour** [comment]
Any thoughts on failure of pre-processing feature?

Whenever I am trying to run it is failing with error, I am providing Sentinel 2 raster as input.

Invalid Data Source: /Applications/--multiprocessing-fork is not a valid or recognized data source.
Plugin SemiAutomaticClassificationPlugin: This plugin is disabled because it previously crashed QGIS.

**Comment by semiautomaticgit** [comment]
If you are having issues, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by rahulkgour** [comment]
> If you are having issues, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

Thanks for listening me.

As you mentioned, I have generated couple of logs,
one while testing dependencies

and the second one while loading data and performing pre-processing function on downloaded sentinel 2 imagery


--> The rasters are fine, as I could perform merge function with QGIS feature.
[logs_while Testing Dependencies.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5492128/logs_while.Testing.Dependencies.txt)
[logs_while performing pre-processing on sentinel 2 data imagery.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5492129/logs_while.performing.pre-processing.on.sentinel.2.data.imagery.txt)

**Comment by semiautomaticgit** [comment]
You are welcome.
It is an installation issue. Please read https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac

**Comment by rahulkgour** [comment]
> You are welcome.
> It is an installation issue. Please read https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac

Hi,

I tried and manually followed the steps https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac
but sadly, no luck.
