### ISSUE TITLE
Classification Mask Error

### ISSUE THREAD

**Issue by Esculenta** [semiautomaticgit/SemiAutomaticClassificationPlugin#129]
Hello,

When I attempt to classify while applying a mask layer to the classification output, I receive an error. Any ideas what may be causing this? When I don't apply the mask layer, there are no problems. 

However, if I use the classified raster image that has not been clipped and try to clip the raster using -> clip raster by mask layer, the new raster image loses all the bands. I have attached the log file if that helps.

Thank you!

[log_error.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5498129/log_error.txt)

**Comment by semiautomaticgit** [comment]
Hello, 
t should be fixed in version 7.0.11. Please update the plugin
