### ISSUE TITLE
Local variable 'u' referenced before assignment - installation issue

### ISSUE THREAD

**Issue by purplexed** [semiautomaticgit/SemiAutomaticClassificationPlugin#13]
Hello Luca,
First of all thank you for your amazing work.
I encountered an issue wile re-installing the SACP, reporting the following:
_This plugin is broken
local variable 'u' referenced before assignment_

My QGis version is 2.14.6 and the SACP version I was trying to install is 5.0.4.

Thanks in advance...!

**Comment by semiautomaticgit** [comment]
Hello, please test the new v.5.0.5.
In case you still get the same error, please describe the OS and QGIS version (32bit / 64bit), and copy the whole error message.
Thank you

**Comment by purplexed** [comment]
Hello,
Thanks for this Luca. It seems to work now.
I think the issue was associated with the QGis version, as I didn't get the "restart QGis to use the plugin" message, and after restarting it, the plugin worked.
I am using Windows 7 x64, and QGis 2.14.6 x64.

**Comment by semiautomaticgit** [comment]
I am glad it worked.
Thank you for the feedback.
