### ISSUE TITLE
Pansharpening Landsat 8 images

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#131]
Hi Luca,

I'm preprocessing Landsat 8 data and I would like to apply a pansharpening with:

Preprocessing tab -> with "Perform pansharpening (Landsat 7 or 8)"

However, SCP only create the PAN for bands B2 B3 B4.

**Comment by semiautomaticgit** [comment]
Hi Pedro,

it is correct because the range of Landsat 8 Panchromatic band  doesn't cover the Near Infrared band (see https://semiautomaticclassificationmanual.readthedocs.io/en/latest/remote_sensing.html#landsat-satellites), so only bands 2, 3, and 4 can be pansharpened.
