### ISSUE TITLE
the prefix "clip" when clipping a raster is not use as spectral bands prefix but to create a new folder "clip_"

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#132]
Hello,
When clipping a band set (ex: landsat5 image of 6 bands) with the clip tool of scp, with the output prefix "clip", the prefix "clip" is not use as prefix for the  clipped spectral bands  but is rather used to create a new folder "clip_" inside which the clipped bands have no prefix, which is not practical as it is then not possible to recogniize the clipped bands from their filenames. confer images.
settings:
![image](https://user-images.githubusercontent.com/44610746/99437756-2bbf3200-2913-11eb-8034-79f42cd72225.png)

outputs: folder "clip_" with clipped bands inside but without prefix
![image](https://user-images.githubusercontent.com/44610746/99437790-38438a80-2913-11eb-82ac-a7fa4fe01a05.png)

**Comment by archyuly** [comment]
Same issue. Using:
![image](https://user-images.githubusercontent.com/74819493/99876553-58848980-2c32-11eb-9b49-09a9fe3495cf.png)

with:
![image](https://user-images.githubusercontent.com/74819493/99876561-663a0f00-2c32-11eb-9990-fa78a7d05e31.png)

**Comment by semiautomaticgit** [comment]
Hello, it should be fixed in version 7.0.16.

**Comment by GITHUBAntoineDENIS** [comment]
OK. Thanks. It works fine now :-)
