### ISSUE TITLE
Error mosaic two bandsets 

### ISSUE THREAD

**Issue by timsonmuc** [semiautomaticgit/SemiAutomaticClassificationPlugin#134]
when starting to mosaic two bandsets with SCP 
QGIS opens multiple new Windows. The process only continues if i close the newly opened windows. Couple seconds later even more QGIS windows appear over and over again. 
I have already tried the "installation issue solve": https://gis.stackexchange.com/questions/366848/scp-plugin-for-qgis-3-10-on-mac

Tried it now on another MacBook Pro macOS Catalina 10.15.7 with QGIS 3.10.4 still the same issue. 

Debug-log shows Error in 
`SemiAutomaticClassificationPlugin.maininterface.mosaicbandsets-mosaicBandSets 223	 ERROR exception: `

no additional details/ stacktrace

thank you for your help!

[log2.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5569699/log2.txt)

**Comment by semiautomaticgit** [comment]
Hello, it seems an installation issue but unfortunately I can't suggest any solution at the moment. 
You could try a virtual machine https://semiautomaticclassificationmanual.readthedocs.io/en/latest/semi-automatic_os.html

**Comment by semiautomaticgit** [comment]
Hello, I think it is related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/144 , so please comment on that post.
Also, it could be related to this possible QGIS issue https://github.com/qgis/QGIS/issues/40472
