### ISSUE TITLE
ERROR 56: SSL CONNECTION

### ISSUE THREAD

**Issue by amontalto416** [semiautomaticgit/SemiAutomaticClassificationPlugin#135]
Hello everyone! I'm using Semi-Automatic Classification plugin on qgis 3.10.9 to download maps, but when I set the parameters and run the command it appeared me the same error: Error 56:SSL CONNECTION. 

Searching on internet I found this issue:

This issue could be related to SSL protocols (TLS v1.1 and TLS v1.2) required for Sentinel-2 download. As described here [https://docs.python.org/2/library/ssl.html](https://docs.python.org/2/library/ssl.html) the protocols TLS v1.1 and TLS v1.2 are available only in Python 2.7.9+ with openssl version 1.0.1+. QGIS could have a previous version of Python where TLS v1.1 and TLS v1.2 are not available. Therefore the Sentinel-2 download process fails.

I tried to re-install the correct the version of python, but I get the same results. Actually some others of my colleagues, that are using a Mac, get the same errors, probably there is something wrong with that. Is there any solutions ?    

Thanks!

**Comment by semiautomaticgit** [comment]
Thank you.
I think it is related to this issue https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/111

**Comment by jar0fair** [comment]
Having the same issue on a Mac when trying to search for Sentinel 2 imagery.

**Comment by semiautomaticgit** [comment]
Hello, 
possibly you can try the solutions provided here https://github.com/gee-community/qgis-earthengine-plugin/ that is:

> Open Finder and double clicking on this file /Applications/Python 3.6/Install Certificates.command. This path may vary depending on how QGIS was installed (Homebrew, macports, native). Then restart QGIS.

**Comment by semiautomaticgit** [comment]
Hello, it seems that /usr/local is not created by default.
A possible solution from https://www.facebook.com/groups/SemiAutomaticClassificationPlugin/permalink/3722826171146887/?comment_id=3740311452731692
In a Terminal: (if you have a libcrypto and libssl in /usr/local/lib this will overwrite them)
`sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.dylib /usr/local/lib/libssl.dylib
sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.dylib /usr/local/lib/libcrypto.dylib`
If usr/local doesn't exist, though it should, even if it's empty. Try:
`sudo mkdir -p /usr/local/lib`
Then, the ln commands and try to do processing on QGIS.

**Comment by OllieRoberts** [comment]
On macOS Big Sur, QGIS 3.12, Python 3.9
1. Error 56 persists when trying to find Sentinel 2. Have tried multiple credentials that work at scihub.
2. Error 40 now persisting when trying to connect to Landsat 8 products.
I have worked through the threads: #72 #111 #135 and tried all the commands.
Anything you need from me, or anything you can help me with?

**Comment by semiautomaticgit** [comment]
> On macOS Big Sur, QGIS 3.12, Python 3.9
> 
> 1. Error 56 persists when trying to find Sentinel 2. Have tried multiple credentials that work at scihub.
> 2. Error 40 now persisting when trying to connect to Landsat 8 products.
> 
> I have worked through the threads: #72 #111 #135 and tried all the commands.
> Anything you need from me, or anything you can help me with?

Hello @OllieRoberts , 
you could try to set the Python executable paths and Python modules in plugin Settings

**Comment by semiautomaticgit** [comment]
This could be related to this issue https://trac.osgeo.org/osgeo4w/ticket/715

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
