### ISSUE TITLE
Satellite interferometry

### ISSUE THREAD

**Issue by denilsonjesus** [semiautomaticgit/SemiAutomaticClassificationPlugin#136]
What is the possibility of including a Satellite Interferometry SAR tool?

**Comment by semiautomaticgit** [comment]
Hello, it could be integrated in the future through ESA SNAP.
In the meantime you can consider creating a custom graph file .xml for this tool https://semiautomaticclassificationmanual.readthedocs.io/en/latest/sentinel1Tab.html

**Comment by semiautomaticgit** [comment]
Hello @javaftw , I'm closing this because the new version 8 of SCP uses Remotior Sensus as processing library.
You may open a feature request at https://github.com/semiautomaticgit/remotior_sensus/issues
Thank you!
