### ISSUE TITLE
Error 40 Unable to connect. Landsat 8, Mac

### ISSUE THREAD

**Issue by jar0fair** [semiautomaticgit/SemiAutomaticClassificationPlugin#139]
Hi there,

While Sentinel imagery is not searchable at all (error 56. Already posted), presently, the Landsat 8 data, is giving a different error. When searching for Landsat 8 data, I will receive the search results, but clicking on any of them for more information, or for a preview, results in error 40: "Unable to connect". Data is not reviewable, nor is it downloadable. There are no other indications of what the issue may be.

**Comment by semiautomaticgit** [comment]
Hello, I think it is related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/135

**Comment by semiautomaticgit** [comment]
Hello, 
possibly you can try the solutions provided here https://github.com/gee-community/qgis-earthengine-plugin/ that is:

> Open Finder and double clicking on this file /Applications/Python 3.6/Install Certificates.command. This path may vary depending on how QGIS was installed (Homebrew, macports, native). Then restart QGIS.

**Comment by semiautomaticgit** [comment]
Hello, it seems that /usr/local is not created by default.
A possible solution from https://www.facebook.com/groups/SemiAutomaticClassificationPlugin/permalink/3722826171146887/?comment_id=3740311452731692
In a Terminal: (if you have a libcrypto and libssl in /usr/local/lib this will overwrite them)
`sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.dylib /usr/local/lib/libssl.dylib
sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.dylib /usr/local/lib/libcrypto.dylib`
If usr/local doesn't exist, though it should, even if it's empty. Try:
`sudo mkdir -p /usr/local/lib`
Then, the ln commands and try to do processing on QGIS.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
