### ISSUE TITLE
Scatter plot - change bands

### ISSUE THREAD

**Issue by csoto666** [semiautomaticgit/SemiAutomaticClassificationPlugin#14]
Despite changing X&Y bands in the scatter plot, this graph keep showing the data for the initial bands
OSX 10 - QGIS 2.16

![screen shot 2016-09-26 at 11 07 56 am](https://cloud.githubusercontent.com/assets/9941392/18844307/fecc4ac2-83d9-11e6-9309-9a87815e0a4d.png)

thanks for your help :)

**Comment by semiautomaticgit** [comment]
Hello,
did you click the button calculate?

**Comment by csoto666** [comment]
yes i did

![scatter_scp](https://cloud.githubusercontent.com/assets/9941392/18858252/d129abde-8427-11e6-9a0a-809222f0deeb.gif)

[Scatter_SCP.pptx](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/494434/Scatter_SCP.pptx)

**Comment by semiautomaticgit** [comment]
Thank you.
I should have fixed this in version 5.0.12. Please test it

**Comment by csoto666** [comment]
Awesome! is fixed thanks a lot

**Comment by semiautomaticgit** [comment]
You are very welcome. Thank you for reporting this issue
