### ISSUE TITLE
 Accuracy Assessment with SCP: FloatingPointError: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by MariaNetaAnalytics** [semiautomaticgit/SemiAutomaticClassificationPlugin#141]
Hi, 
While doing an accuracy assessment, with the SCP pluggin in QGIS3.10, I got an error from python "FloatingPointError: invalid value encountered in double_scalars" (**see image below**). For this, I have checked the validation data that I inserted as input values, but they look fine (format, MC, C_ID, etc), so I can not understand why this didn't work. Thanks

![image](https://user-images.githubusercontent.com/60387852/100882131-bc1a7c80-34a6-11eb-91a5-e6c22f88b557.png)

**Comment by semiautomaticgit** [comment]
Hi, 
could you please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
Hello, it could be related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/113
If not, please reopen this
