### ISSUE TITLE
Cannot Execute SCP for Landsat8 Preprocessing - Mac QGIS3.10

### ISSUE THREAD

**Issue by sysy122** [semiautomaticgit/SemiAutomaticClassificationPlugin#148]
I get an error when executing preprocessing for landsat 8 images in SCP ver. 7.2.6 on qgis mac 3.10.

A new QGIS window pops up while the previous is still running  and I get an error saying "EOFError". Someone already posted on stack exchange with the same issue (https://gis.stackexchange.com/questions/382346/cannot-run-semi-automatic-classification-scp-on-mac?newreg=c3b3d8a9c212497080ff37a56afddc3b).

Please help!

**Comment by semiautomaticgit** [comment]
Hello, I think it is related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/144 , so please comment on that post.
Also, it could be related to this possible QGIS issue https://github.com/qgis/QGIS/issues/40472
