### ISSUE TITLE
Is available SCP for Pop Os ?  

### ISSUE THREAD

**Issue by barja8** [semiautomaticgit/SemiAutomaticClassificationPlugin#152]
Hello, time ago I had installed **SCP** without nothing problems, but now  I have this error message.
Could you help me please ? 
The wrong message that show me is the next: 

```{r}
Falló la instalación del complemento: Error transferring https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/version/7.5.4/download/ - server replied: Not FoundU
```
**Thank a lot .**
![Captura de pantalla de 2021-02-02 21-40-37](https://user-images.githubusercontent.com/23284899/106690165-4d899600-659f-11eb-8765-ae3410a3516c.png)
![Captura de pantalla de 2021-02-02 21-40-53](https://user-images.githubusercontent.com/23284899/106690182-567a6780-659f-11eb-9147-51de8222490e.png)

**Comment by semiautomaticgit** [comment]
Hello, I think it is a QGIS issue.
I opened this ticket https://github.com/qgis/QGIS/issues/41336

**Comment by semiautomaticgit** [comment]
It should be fixed now.
