### ISSUE TITLE
Error SCP 7.5.6 Sentinel-2 download.

### ISSUE THREAD

**Issue by Jules428** [semiautomaticgit/SemiAutomaticClassificationPlugin#153]
Error [56] SSL Connection error when downloading Sentinel-2 images 
Mac OS 11.2

**Comment by semiautomaticgit** [comment]
Hello, I think it is a duplicate of https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/135
Please try the suggested solutiob
