### ISSUE TITLE
Error with Random Forest Classification

### ISSUE THREAD

**Issue by MelStei** [semiautomaticgit/SemiAutomaticClassificationPlugin#156]
Hi Luca, 

I was trying to do a Random Forest Classification, but I get the error "Select at least one raster band". However, I defined and selected my bandset. Also I created the training data. Where could the error be? I have attached some screenshots from my settings. 

Any help would be greatly appreciated. 

Thank you
Melanie

![Error](https://user-images.githubusercontent.com/79172870/108126807-90249580-70aa-11eb-9664-cdee9f89e96b.JPG)

![image](https://user-images.githubusercontent.com/79172870/108126964-ceba5000-70aa-11eb-9e3f-7e48e1f83e2f.png)

**Comment by semiautomaticgit** [comment]
Hi Melanie, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
