### ISSUE TITLE
Error trying load Sentinel-2 images from directory

### ISSUE THREAD

**Issue by FranklinJS** [semiautomaticgit/SemiAutomaticClassificationPlugin#157]
Trying execute DOS correction in Sentinel-2 images from directory, get this error:

> 2021-03-02 11.31.31.438572	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-populateTable 111	 ERROR exception: list index out of range
> 2021-03-02 11.31.31.445572	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-inputSentinel 50	C:/Analise_RenovaBio_2021/IMG_SNTL2_20210219/S2A_MSIL2A_20210219T134211_N0214_R124_T22KCE_20210219T160834/S2A_MSIL2A_20210219T134211_N0214_R124_T22KCE_20210219T160834.SAFE/GRANULE/L2A_T22KCE_A029579_20210219T134210
> 2021-03-02 11.31.39.584660	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-populateTable 111	 ERROR exception: list index out of range
> 2021-03-02 11.31.39.590662	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-inputSentinel 50	C:/Analise_RenovaBio_2021/IMG_SNTL2_20210219/S2A_MSIL2A_20210219T134211_N0214_R124_T22KCE_20210219T160834/S2A_MSIL2A_20210219T134211_N0214_R124_T22KCE_20210219T160834.SAFE/GRANULE/L2A_T22KCE_A029579_20210219T134210/IMG_DATA/R10m

QGIS Instalation

> Versão do QGIS
> 3.16.4-Hannover
> Código da versão do QGIS
> 654e76b3cb
> Compilado sobre Qt
> 5.11.2
> Rodando sobre Qt
> 5.11.2
> Compilado sobre GDAL/OGR
> 3.1.4
> Rodando sobre GDAL/OGR
> 3.1.4
> Compilado sobre GEOS
> 3.8.1-CAPI-1.13.3
> Rodando sobre GEOS
> 3.8.1-CAPI-1.13.3
> Compilado no SQLite
> 3.29.0
> Executando contra SQLite
> 3.29.0
> Versão do cliente PostgreSQL
> 11.5
> Versão SpatiaLite
> 4.3.0
> Versão do QWT
> 6.1.3
> Versão QScintilla2
> 2.10.8
> Compilado com PROJ
> 6.3.2
> Em execução com PROJ
> Rel. 6.3.2, May 1st, 2020
> Versão SO
> Windows 10 (10.0)
> Ativar complementos python
> profiletool; 
> quick_map_services; 
> SemiAutomaticClassificationPlugin; 
> processing

**Comment by semiautomaticgit** [comment]
Hello, if you don't download the images with SCP, you should first rename the bands in order to have the band number at the ending of the name e.g. _B02.jp2

**Comment by FranklinJS** [comment]
Thank you! I have downloaded this from copernicus hub directly, the archive name terminate with _10m (resolution), renamed it and voilá.

**Comment by semiautomaticgit** [comment]
You are very welcome
