### ISSUE TITLE
I try to classify Sentinel-2 images using SCP plugin and i get this error "AttributeError: 'QSortFilterProxyModel' object has no attribute 'refreshLayerLegend'  Traceback (most recent call last)"

### ISSUE THREAD

**Issue by boalidtank67** [semiautomaticgit/SemiAutomaticClassificationPlugin#166]

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
Hello, it should be solved in version 7.8.1. Please update the plugin
