### ISSUE TITLE
QGIS crashes when missing dependecies

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#17]
Hi Luca,

I've found that, in Windows (OSGeo4W 64bits), I can install SCP Plugin (5.1.x) without some dependencies, and without any alert message in Plugin Manager. Then, after restarting QGIS, I get this messages in "notification bar":
- Semi-Automatic Classification Plugin: Please, restart QGIS for executing the Semi-Automatic Classification Plugin. Possible missing dependecies.
- Semi-Automatic Classification Plugin: Please, restart QGIS for executing the Semi-Automatic Classification Plugin.

As they are temporary notifications, they may go unnoticed, and SCP does not show up, and QGIS crashes when closing.

I was with SciPy missing. After installing it, everything runs ok.

It would be great if, when installing SCP in Plugin Manager, it warned about the missing dependencies.

Thank you very much for your work!

Best regards,
Pedro Venâncio

**Comment by semiautomaticgit** [comment]
Hi Pedro Venâncio,

thank you for reporting this.
I am aware of this dependency issue, I'll try to add some information to the message.

Cheers,
Luca

**Comment by semiautomaticgit** [comment]
I have added the missing dependency to the message in version 5.2.2.

Cheers,
Luca.
