### ISSUE TITLE
Não inicia o dowloard de imagens

### ISSUE THREAD

**Issue by Evandro182** [semiautomaticgit/SemiAutomaticClassificationPlugin#170]
Ao seguir os passos de dowlaord de imagens funciona tudo certo, mas quando clica para baixar apenas faz os bips e nada acontece.

Ao fazer debug consta o seguinte erro.

2021-04-20 18.06.09.615164	SemiAutomaticClassificationPlugin.maininterface.settings-testSNAPSubprocess 448
ERROR exception: [WinError 87]

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by Evandro182** [comment]
[ERRO.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6370187/ERRO.txt)

**Comment by semiautomaticgit** [comment]
Thank you for the log file, however I can't find any information about the download. 
Please repeat the same steps causing the issue and attach the log file again.

**Comment by Evandro182** [comment]
![image](https://user-images.githubusercontent.com/33988061/115973963-75015680-a52f-11eb-8640-7172568b7e1f.png)


So, I remade the Debug and did not present anything different from the previous document.
For some random reason, I decided to deselect "only if preview in Layers" when I pressed "run" the image started the dowwloard.

**Comment by semiautomaticgit** [comment]
Thank you for your feedback.
This is as designed. If the checkbox is activated then only images having previews added to QGIS layers are downloaded.
