### ISSUE TITLE
Issues with download from Copernicus Scihub

### ISSUE THREAD

**Issue by MG977** [semiautomaticgit/SemiAutomaticClassificationPlugin#173]
Hi there,

I have been having trouble downloading data from Copernicus Scihub with SCP for a few days:

1- The button "Display preview of highlighted images in map" does not work anymore.

2- Sometimes I get:
Error [50] : Internet error:unknown url type: ''
Error [40] : Unable to connect

On the other hand, the download from other sources is still fine, and I can add the image previews to layers. 

I do not understand if it is a Scihub problem or if something broke in SCP.  SCP is updated, and I also tried a clean run with a new profile. Still, the issue is there.

Any advice?

Marco

**Comment by semiautomaticgit** [comment]
Hi, 
usually this happens if the images are in the long term archive or the acquisition date is very recent and the preview isn't available. However, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this, but feel free to reopen if you still get he same issue. Thank you
