### ISSUE TITLE
Problem downloading satellite images

### ISSUE THREAD

**Issue by josinc** [semiautomaticgit/SemiAutomaticClassificationPlugin#174]
When I try to download Sentinel 2 images, the preview inside plufin window was not visible. Then I clicked download and selected the target folder. But nothing happened other than just playing a sound.
![qgis-bin-g7_6zSCi4SDDj](https://user-images.githubusercontent.com/22650207/117578908-48903180-b10e-11eb-9c33-78ac8b29dbb1.png)

**Comment by semiautomaticgit** [comment]
Hello, this happens if the acquisition date is very recent and the preview isn't available. You should be able to download the images unchecking the option "Only if preview in layers"

**Comment by josinc** [comment]
Thank you, that worked.
Still 'Display preview' button is not working.
I click the button, but nothing happens.

**Comment by semiautomaticgit** [comment]
Please update the plugin to version 7.8.32 .
If you still have this issue please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
