### ISSUE TITLE
Creating ROIs : information Select a raster; raster is not loaded 

### ISSUE THREAD

**Issue by 01zeng** [semiautomaticgit/SemiAutomaticClassificationPlugin#175]
Hi, 
While I try to create a ROIs in QGIS with SCP , this information appear :  **_Select a raster; raster is not loaded_** 
Can anyone give me a hand with this issue? 

Thanks in advance

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this, but feel free to reopen if you still get he same issue. Thank you
