### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'str'

### ISSUE THREAD

**Issue by JC-VG** [semiautomaticgit/SemiAutomaticClassificationPlugin#179]
I was pre-processing some HDF files using the Semi-Automatic Classif Plugin in Qgis.

The process stopped and an error popped up. SCP freezes and does not record the log file, nor process the images. This is what the error says:

TypeError: unsupported operand type(s) for /: 'float' and 'str'

I have tried old HDF files and reinstall SCP, etc. Same error message.
[SCP_log_error_hdfs.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6625936/SCP_log_error_hdfs.txt)
[SCP_log file_error_2.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6625940/SCP_log.file_error_2.txt)

I'll appreciate any solution to this.
Regards,
JC

**Comment by semiautomaticgit** [comment]
Hello, please update the plugin to version 7.8.27, it should be solved.

**Comment by JC-VG** [comment]
Thanks a lot Luca. Really appreciated.
I would've liked to know the real issue with the "float" and "str".
