### ISSUE TITLE
Error 38 : unable to load raster

### ISSUE THREAD

**Issue by brahma199** [semiautomaticgit/SemiAutomaticClassificationPlugin#180]
CRITICAL    Error [38] : Unable to load raster
   
While dealinmg with sentinel2 data , the above message occuring everytime even though i have entered all the files correctly and with no spaces in the directory.
please help me out from this problem 
i tried all methods and all type of sentinel imageries but still same problem arising 
thank you in advance.

please refer image attached
![error](https://user-images.githubusercontent.com/86707565/123914658-41163780-d99d-11eb-828a-2d4c34e68b43.png)

**Comment by semiautomaticgit** [comment]
Hello, it should be fixed, please update the Semi-Automatic Classification Plugin to version 7.8.32

**Comment by brahma199** [comment]
> Hello, it should be fixed, please update the Semi-Automatic Classification Plugin to version 7.8.32

Excuse me sir i have that version only  7.8.32 and QGIS also latest version 3.16.8

**Comment by semiautomaticgit** [comment]
> > Hello, it should be fixed, please update the Semi-Automatic Classification Plugin to version 7.8.32
> 
> Excuse me sir i have that version only 7.8.32 and QGIS also latest version 3.16.8
Please update to version 7.8.33. 
If you still have issue, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by joaonaime** [comment]
Hello, I'm also having the same issue (error[38]). I'm running QGIS 3.24 and SCP version 7.10.5 - Matera.
Has someone solved this problem?
