### ISSUE TITLE
ASTER Bands

### ISSUE THREAD

**Issue by JMejuto** [semiautomaticgit/SemiAutomaticClassificationPlugin#181]
Hello,

I am having problems with the new version and ASTER images, after loading it, the pre-processing tab shows no bands information. I have tried several versions of QGIS and the problem persists.

Thank you very much for the time

[log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6788069/log.txt)
![Captura de pantalla de 2021-07-05 08-58-09](https://user-images.githubusercontent.com/36420398/125009751-6270c680-e022-11eb-8c9f-bf00f78a8cfd.png)

**Comment by semiautomaticgit** [comment]
Hello and thank you for the log file.
Was the ASTER image downloaded using the Semi-Automatic Classification Plugin?

**Comment by JMejuto** [comment]
Thank you for your reply,  it was downloaded using Landviewer.

**Comment by semiautomaticgit** [comment]
You are welcome.
I'll look into this, but I suspect it is an issue related to the format of data.

**Comment by antoine-gs** [comment]
Having the same issue. A colleague could open the same hdf file on a different computer with an older version of the plugin.

**Comment by JMejuto** [comment]
> You are welcome.
> I'll look into this, but I suspect it is an issue related to the format of data.

I have tried the same data in debian (same qgis and scp versions) and worked perfectly. So, I guess is a problem in Manjaro.

**Comment by semiautomaticgit** [comment]
> Having the same issue. A colleague could open the same hdf file on a different computer with an older version of the plugin.
> EDIT: my problem was that aster is hdf4 while my system had support for hdf5. In my case the issue was not trivial in that I could not install hdf4 for gdal without breaking other dependencies. I set up a virtual environment and used the python API, which was a quick enough fix for me! In other words, nothing directly related to the plugin.

Thank you for your feedback!

**Comment by semiautomaticgit** [comment]
> > You are welcome.
> > I'll look into this, but I suspect it is an issue related to the format of data.
> 
> I have tried the same data in debian (same qgis and scp versions) and worked perfectly. So, I guess is a problem in Manjaro.

Thank you, then I'm closing this, but of course feel free to reopen in case of issues.
