### ISSUE TITLE
Unable to export and display low resolution preview of sentinel 2 image in the main  map of QGIS using semi automatic classification plugin

### ISSUE THREAD

**Issue by cengr2009** [semiautomaticgit/SemiAutomaticClassificationPlugin#182]
Dear All, I am using QGIS V3.16 and I am able to search sentinel 2 images using  semi automatic classification plugin. However in order to check what image is crossing my area of interest , I try to click the " Display preview of highlighted images in the map" , however the preview is not displayed on the main map, thus it is very hard to find which image is to download. Please help me in this regard. Best Regards

**Comment by semiautomaticgit** [comment]
Hello, usually previews are not available if the images are acquired very recently.
To better understand the issue, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error.

**Comment by semiautomaticgit** [comment]
It should be solved in the last plugin version.
