### ISSUE TITLE
Copernicus Sentinel-2: Major Products Upgrade Upcoming

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#186]
Dear @semiautomaticgit 

In case you are not aware of this change, I leave here the news from ESA:

https://sentinels.copernicus.eu/web/sentinel/-/copernicus-sentinel-2-major-products-upgrade-upcoming/1.9?redirect=%2Fweb%2Fsentinel%2Fhome

Best regards

**Comment by semiautomaticgit** [comment]
Dear @PedroVenancio ,

thank you for the information, it is good to keep track of changes.

Best regards

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Thank you!
