### ISSUE TITLE
Raster stack of bands do not get created on macosx

### ISSUE THREAD

**Issue by kaarigar** [semiautomaticgit/SemiAutomaticClassificationPlugin#187]
I am using Landsat 8 bands to create virtual raster and stacked bands. However, only the virtual raster gets created - the band stack geotiff doesn't get created. I am using QGIS Hannover LTR 3.16.11

<img width="1366" alt="Screen Shot 2021-10-03 at 5 31 09 PM" src="https://user-images.githubusercontent.com/44623903/135778897-be1c8faa-3c4e-4817-9b11-4af77112be83.png">

**Comment by semiautomaticgit** [comment]
Hello, I think it is an installation issue (maybe related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/144).

Please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
> Hello @semiautomaticgit
> 
> Maybe is not related to #144


Hello @jsparedes , it seems an installation issue.
You can try to follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
