### ISSUE TITLE
Error [56]: SSL connection error

### ISSUE THREAD

**Issue by Deepay26** [semiautomaticgit/SemiAutomaticClassificationPlugin#190]
Hello :)
Trying to use SemiAutomaticClassificationPlugin but when i tryed to select images from sentinel 2 for my area i have the Error [56]: SSL connection error. 
When i check the dependencies, SNAP Subprocess is failing.
![error](https://user-images.githubusercontent.com/28987782/137959342-08270de1-06c6-4adc-9c8e-36087eee90c8.png)
I leave here the log error.
[error.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/7375441/error.txt)
Im using Windows 10 and Odense Version of QGIS (3.20.3)

**Comment by semiautomaticgit** [comment]
Hello @Deepay26 , it could be related to https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/135, but unfortunately it is still not solved

**Comment by semiautomaticgit** [comment]
This could be related to this issue https://trac.osgeo.org/osgeo4w/ticket/715

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
