### ISSUE TITLE
Compute signatures from .shp file

### ISSUE THREAD

**Issue by demagist** [semiautomaticgit/SemiAutomaticClassificationPlugin#194]
Hello,

is there a way to import a shapefile directly into the tool to compute signatures ?

or at least, indications on how to convert a shapefile to the appropriate format of a .scp file ?

Many thanks for your answer

Laurent

**Comment by semiautomaticgit** [comment]
Hello Laurent,
yes, it is possible to import a shapefile using this tool (after the creation of a Band set and an empty training input)  https://semiautomaticclassificationmanual.readthedocs.io/en/latest/importSignaturesTab.html
