### ISSUE TITLE
cannot define a search area on linux

### ISSUE THREAD

**Issue by saultdon** [semiautomaticgit/SemiAutomaticClassificationPlugin#20]
Afternoon,

I'm trying to draw a search area on the map (after loading OSM Mapnik layer, in EPSG 3857) and on the SCP landsat download tab, I click the "set area in the map" red cross button and my cursor changes in the map canvas.

But when I click and drag to make a box, no box is drawn and instead, only the UL X/Y boxes are filled out, and not the LR X/Y boxes (these are empty).

I have SCP v5.2.1 loaded, running QGIS 2.18.0 and OS is Arch Linux.

**Comment by semiautomaticgit** [comment]
Hello,

thank you for using SCP.
You should left click to set the UL point and right click to set the LR point.
Please see http://semiautomaticclassificationmanual-v5.readthedocs.io/en/latest/main_interface_window.html#search-area
