### ISSUE TITLE
Can't upload vector to clip the multi raster 

### ISSUE THREAD

**Issue by Shaileshdesai76** [semiautomaticgit/SemiAutomaticClassificationPlugin#204]
I have create bandset using seven band (landset 7) and now I'm clipping it with my vector(shape file), I have already tick the option, but I can't browse or select vector file 😔.

I'm new at semi automatic plugin

**Comment by semiautomaticgit** [comment]
Hello @Shaileshdesai76 , please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by Shaileshdesai76** [comment]
Thank you very much
It's worked well now.
Thank you
