### ISSUE TITLE
Output cluster classes different to input

### ISSUE THREAD

**Issue by LF386** [semiautomaticgit/SemiAutomaticClassificationPlugin#205]
I'm using Sentinel 2 imagery to create land-use classifications. I've attempted a number of times to create 10 classes following the instructions on the blogspot webisite, however the output has ranged from 4-18 classes and not once resulted in 10 as aimed for.

Can anyone enlighten me to why this may be, or whether there is in fact an issue with the plugin?

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this for lack of feedback, but please reopen it if you still have this issue.
