### ISSUE TITLE
Python error when creating new polygon for spectral signature

### ISSUE THREAD

**Issue by frnmz** [semiautomaticgit/SemiAutomaticClassificationPlugin#206]
**Here's my system info:**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.0
GDAL/OGR version | 3.3.2
Compiled against PROJ | 8.2.0.%3.%4 | Running against PROJ | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.9.2-CAPI-1.14.3
SQLite version | 3.36.0
PDAL version | 2.3.0
PostgreSQL client version | 13.4
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 35 (Workstation Edition)
  |   |   |  
Active Python plugins
OSMDownloader | 1.0.3
CalculateGeometry | 0.6.4
ORStools | 1.5.0
travel_time_platform_plugin | 1.5.2
AcATaMa | 19.11.21
SemiAutomaticClassificationPlugin | 7.10.5
MetaSearch | 0.3.5
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

**The problem:**

When creating polygon with this tool:
![image](https://user-images.githubusercontent.com/18339774/150274381-f88b6ca9-5643-41aa-9870-a3c76c24f927.png)
I got python error that said:

```
2022-01-20T11:28:45     WARNING    Traceback (most recent call last):
              File "/home/lam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2652, in clckR
              self.addHighlightPolygon(cfg.lstROI, 1)
              File "/home/lam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2527, in addHighlightPolygon
              clr.setAlpha(rT)
             TypeError: setAlpha(self, int): argument 1 has unexpected type 'float'
```

I've tried reinstalling the plugin but still got the same results.

**Comment by semiautomaticgit** [comment]
Hello, thank you for this information. I'll look into this issue

**Comment by frnmz** [comment]
@semiautomaticgit I don't know if this related, but AcATaMa plugin is displaying similiar python error message.
See: https://github.com/SMByC/AcATaMa/issues/12#issuecomment-1022830101

**Comment by semiautomaticgit** [comment]
> @semiautomaticgit I don't know if this related, but AcATaMa plugin is displaying similiar python error message. See: [SMByC/AcATaMa#12 (comment)](https://github.com/SMByC/AcATaMa/issues/12#issuecomment-1022830101)

Thank you for reporting this

**Comment by frnmz** [comment]
Strangely it works fine on QGIS Flatpak on Fedora Silverblue 35...

**Comment by simonericmoon** [comment]
Hello all, I have the same issue with the latest Version of QGIS Tisler on ubuntu, but not on a windows virtual machine.
Any idea how we can fix this issue?

**Comment by SimoParmeg** [comment]
"/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2652, in clckR self.addHighlightPolygon(cfg.lstROI, 1)
File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2527, in addHighlightPolygon
clr.setAlpha(rT)
TypeError: setAlpha(self, int): argument 1 has unexpected type 'float'

I see in line 2652:

rT = 255 - cfg.ROITrnspVal * 255 / 100
clr.setAlpha(rT)

/ 100 will return a float, maybw should use //100

I'm just guessing, I don't know what the script does, I'm just helping a friend with a problem

**Comment by semiautomaticgit** [comment]
Hello, please update the SCP to version 7.10.7, it should fix this issue.
