### ISSUE TITLE
'NoneType' object is not subscriptable while performing clustering

### ISSUE THREAD

**Issue by benert007** [semiautomaticgit/SemiAutomaticClassificationPlugin#208]
Hey everyone.

I have been trying to perform K-means and ISODATA clustering but am not able to, thanks to this 'NoneType' object is not subscriptable error. My QGIS version is currently 3.16 with the SCP version being 7.10.5 - Matera running on Windows 11 OS.
I'm attaching a snap of the error message.

![image](https://user-images.githubusercontent.com/98613740/151605530-e427d51b-cbf7-42d2-bb84-c6e33e5bb52e.png)

Thanks Luca

**Comment by semiautomaticgit** [comment]
Hello,
please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by benert007** [comment]
[debug_log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/7963233/debug_log.txt)
[Error_message.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/7963234/Error_message.txt)

Hey Luca.

PFA the debug log file and the python error message.

Thanks again Luca

**Comment by benert007** [comment]
Hi,

Have replied to this email by uploading the file in the forum.

Looking forward to hearing from you.

Regards,
Benin

**Comment by semiautomaticgit** [comment]
Thank you @benert007 for the log file.
I would suggest to update QGIS.

**Comment by benert007** [comment]
I had first used SCP in the latest version of QGIS. And that is where the issue began. So I installed QGIS 3.16, it being the most stable, but the problem persued.

**Comment by semiautomaticgit** [comment]
Could you please try to use this sample [dataset](https://docs.google.com/uc?id=1cph9rCQ1oiWgRGusgRkjUWwLW3JEwqUK) ?

**Comment by benert007** [comment]
The sample dataset was classified perfectly. No errors or issues.
So I used another dataset that I already had but got the above-mentioned error.

**Comment by semiautomaticgit** [comment]
> The sample dataset was classified perfectly. No errors or issues. So I used another dataset that I already had but got the above-mentioned error.

Thank you. 
What images are you using?

**Comment by benert007** [comment]
Landsat 8 and LISS 3 images

**Comment by semiautomaticgit** [comment]
Possibly it is a memory issue. Please check that there is enough disk space (during the process large temporary files can be created)

**Comment by benert007** [comment]
Hi Luca.

I had the images processed in another with more free memory and it worked. Thanks a lot for your help! Talking with you has been awesome!
