### ISSUE TITLE
Landsat 9 Data Access

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#211]
Dear @semiautomaticgit 

This is just a feature request to Landsat 9 data access, now that it is already available:

https://www.usgs.gov/landsat-missions/landsat-data-access

Thank you very much Luca!

**Comment by semiautomaticgit** [comment]
Thank you @PedroVenancio , I'll try to add Landsat 9 to the available products in SCP

**Comment by Tshisi-77** [comment]
Dear semiautomaticgit

Do you have approximate time frame, as I have landsat9 to be  pre-processed.
regards Tshisi

**Comment by semiautomaticgit** [comment]
Dear @Tshisi-77 , the update could be in a few weeks

**Comment by semiautomaticgit** [comment]
I have updated the plugin to version 7.10.6.
It now allows for the preprocessing of Landsat 9 data.
Landsat 9 direct download is still not available.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP, which allows for downloading the Harmonized Landsat and Sentinel-2 data.
Thank you!
