### ISSUE TITLE
Preprocessing of Landsat 8 and 9  of Collection 2 Level 2

### ISSUE THREAD

**Issue by semiautomaticgit** [semiautomaticgit/SemiAutomaticClassificationPlugin#217]
Preprocessing of Landsat 8 and 9  of Collection 2 Level 2 is affected by an issue causing incorrect values of temperature

**Comment by Gajuan99** [comment]
Hi! Actuallly I am having problems when preprocessing landsat 8 satellite images. When executing the command through the SCP, it generates blank raster layers and with values ​​that do not correspond to raidance values.

**Comment by semiautomaticgit** [comment]
Hello @Gajuan99 , it should be a stretching issue related to NoData value. You can edit the stretching or uncheck the option "Use value as NoData" in preprocessing
