### ISSUE TITLE
CLIP MULTIPLE RASTER WITH CLIP VECTOR results in BINARY IMAGE

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#218]
Hello Lucas,
When I clip a landsat-5 image in scp with the clip multiple rasters tool and using a shapefile vector as clip feature the resulting clipped image is a binary image (0 / 1). If I use instead the red-orange cross to define the ROI, resulting image is OK. For the clip feature: everything is in the same SCR (project, image, clip). Previously it was working fine. Not anymore. 
I use the last version of SCP. QGIS 3.16. Windows 7. (but same problem on other more recent computers and last version of QGIS)
Best regards,
Antoine

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS ,
thank you for reporting this.
I'll look into it.

Best regards

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , please update the SCP to version 7.10.7.
It should fix the clip issue, although you should preprocess the images again.
