### ISSUE TITLE
the NDVI and EVI values are not displayed next to the cursor, even after enabling it in the ROI options

### ISSUE THREAD

**Issue by rvrmohan** [semiautomaticgit/SemiAutomaticClassificationPlugin#219]
I am using ver 7.10.6 of SCP. The NDVI and EVI values are not appearing next to the cursor. I checked the 'display' option in ROI options, still it does not work.

**Comment by semiautomaticgit** [comment]
Hello @rvrmohan , please check that the central wavelength is defined in the Band set https://semiautomaticclassificationmanual.readthedocs.io/en/latest/bandSetTab.html

**Comment by rvrmohan** [comment]
Dear Luca,

Thanks a lot and it now works.

Ramamohan

**Comment by semiautomaticgit** [comment]
You are very welcome
