### ISSUE TITLE
QGIS 2.18: Error in NUMPY and GDAL 2.1

### ISSUE THREAD

**Issue by cobie1kenobi** [semiautomaticgit/SemiAutomaticClassificationPlugin#22]
I recently upgraded to Ubuntu 16.0 and installed QGIS 2.18. As I tried the SACPlug-in, this error came:

ERROR 1: NUMPY driver was compiled against GDAL 2.1 but current library version is 1.11

Segmentation fault (core dumped)

I have basic ubuntu/linux capability so I would really appreciate all your help.

**Comment by semiautomaticgit** [comment]
Hello,
this is not a plugin error, but a dependency issue.
As you can read in the error message it seems that you have installed a python numpy version that is for GDAL 2, while you have installed GDAL 1. You should install GDAL 2 or install python numpy for GDAL 1.
