### ISSUE TITLE
Is there a way of using CARTOSAT or any other source of images ?

### ISSUE THREAD

**Issue by rvrmohan** [semiautomaticgit/SemiAutomaticClassificationPlugin#220]
The SCP is very comprehensive in its features and user-friendly too. But, is there a way of using images from other satellites, that are not included in the download sources ?

**Comment by semiautomaticgit** [comment]
Thank you @rvrmohan for your kind words.
You can use any raster in SCP. Of course, the preprocessing of satellites that are not included in the SCP tools should be performed using Band calc for calculations. For instance read this tutorial https://fromgistors.blogspot.com/2021/08/image-conversion-to-reflectance.html

**Comment by rvrmohan** [comment]
Dear Luca,

Thanks a lot for your patience with me. I am in the process of learning and
exploring the SCP, though I have been using QGIS for quite some time.
Therefore, my questions may sometimes sound rudimentary.

Thanks and regards,

Ramamohan

**Comment by semiautomaticgit** [comment]
You are very welcome.
Every question is useful.

Best regards
