### ISSUE TITLE
Whether land surface temperature values depend on time of the day of the satellite pass ?

### ISSUE THREAD

**Issue by rvrmohan** [semiautomaticgit/SemiAutomaticClassificationPlugin#224]
I had gone through your video 'Estimation of Land Surface Temperature with Landsat and ASTER'. Obviously, the surface temperature calculated from the emissivity values varies with the season in a year. However, does it also depend on the time of the day at which the satellite took the image of a particular area ? If yes, secondly, is there a way of finding out the time of the day of a particular image taken on a particular day ?

Thanks in advance for your always useful and prompt replies.

**Comment by semiautomaticgit** [comment]
Hello @rvrmohan ,
yes, the temperature varies with the time of the day.
The time of acquisition is included in the metadata of the image (usually it is in the morning).
