### ISSUE TITLE
Landsat data not available

### ISSUE THREAD

**Issue by terezapohankova** [semiautomaticgit/SemiAutomaticClassificationPlugin#237]
Hi,
I am trying to download Landsat Data using the plugin but no luck. Everytime I am told that no image was found and to use larger ROI area. I used almost the whole country but still do not get any Landsat data. Works great for Sentinels.

**Comment by semiautomaticgit** [comment]
Hi @terezapohankova , unfortunately images acquired after 01/01/2022 are not available though the service used for searching images.
Hopefully they will fix this issue soon.

**Comment by Svankarl** [comment]
@semiautomaticgit but even if searching images from earlier periods than that, I get "No image found. Try with a larger area".

**Comment by semiautomaticgit** [comment]
@Svankarl thank you. Probably they have change some parameters of the service.
I'll try to look into this.

**Comment by cubarro** [comment]
> @semiautomaticgit but even if searching images from earlier periods than that, I get "No image found. Try with a larger area".

Same problem here.  No landsat data at all.

**Comment by GITHUBAntoineDENIS** [comment]
Same for me

**Comment by jgrn307** [comment]
Hi, I'm a new user and was wondering if this was ever fixed?  I also can't find Landsat data.

**Comment by semiautomaticgit** [comment]
Hi @jgrn307 , it is still not fixed but it will be in the next version wish should be published by the end of this year

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
