### ISSUE TITLE
Bug when not loading a preview

### ISSUE THREAD

**Issue by tdubbeldam** [semiautomaticgit/SemiAutomaticClassificationPlugin#238]
When downloading a Sentinel-2 image the download fails if a preview has not first been added to the layers in QGIS.

**Comment by semiautomaticgit** [comment]
Hello, this is a feature of the tool.
If you uncheck the option "Only if preview in Layers", all the images in the table will be downloaded
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/downloadProductsTab.html#download-1
