### ISSUE TITLE
Training ROI warning during classification

### ISSUE THREAD

**Issue by lisa-kb** [semiautomaticgit/SemiAutomaticClassificationPlugin#239]
When creating training ROI for classification of a Landsat 8 image in QGIS 3.22 I get a warning message:  'Warning [12]: The following signature will be excluded if using Maximum Likelihood'.  Even when making larger polygons I still get the warning, and only bands 2-7 were used as input for converting the bands to reflectance.  (found this in another thread: https://www.facebook.com/groups/SemiAutomaticClassificationPlugin/posts/1984405614988960/?comment_id=5342870215809133)   
The strange thing is just one day before I could do the classification of the same image and did not get a warning message. 
I also noticed that in the day before, the bandset definition for Landsat 8 in the wavelength quick settings was 'Landsat 8 OLI [bands 2,3,4,5,6,7]' and the next day when the classification did not work, the wavelength quick settings in the SCP window was suddenly 'Landsat 8 OLI [bands 1,2,3,4,5,6,7]' and the composite image was not the same as the day before (due to the incorrect wavelength definitions I suppose.. band 2 was defined as band 1 and so on) Could this be related to the problem with the training ROI's and is there a way to change it back/resolve this?  I am fairly new at this, so maybe the solution is really obvious but I am not aware of this.
![Capture2](https://user-images.githubusercontent.com/115106725/194133531-a619a8d4-142d-45ed-bd71-950220938e81.PNG)
![Capture1](https://user-images.githubusercontent.com/115106725/194133538-a44b576c-ba7e-4691-b77a-e34a4e63f0c4.PNG)

**Comment by semiautomaticgit** [comment]
Hello @lisa-kb  please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
The issue could be related to pixel values or missing bands.
About the change of the wavelength quick settings, probably you updated the plugin. However, if you opened a QGIS project with a saved Band set, the wavelength center is loaded  from the project.
Also, please have a look at the basic tutorials https://semiautomaticclassificationmanual.readthedocs.io/en/latest/tutorials.html

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
