### ISSUE TITLE
SCP Menu "DOWNLOAD PRODUCTS" NOT REACHABLE from the SCP main tool window

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#241]
Hello,
the SCP Menu "DOWNLOAD PRODUCTS" (telecharger de produit " in french) is NOT REACHABLE from the SCP main tool window when clicking on it. From the Main QGIS menu bar, it is ok. But in the SCP tool window, this menu doesn't react: nothing happens. So we have to go back to the QGIS menu to access it. Confer image below.

![image](https://user-images.githubusercontent.com/44610746/200130765-4cdfac3d-765d-4b02-985b-5d796077c1af.png)

**Comment by semiautomaticgit** [comment]
Hello, thank you for reporting this.
I think it is related to the translation file. I'll look into it.

**Comment by semiautomaticgit** [comment]
Hello, it should be fixed in version 7.10.10.
