### ISSUE TITLE
Undetected vector for clip multiple raster

### ISSUE THREAD

**Issue by azainurrafi-zr** [semiautomaticgit/SemiAutomaticClassificationPlugin#243]
can you offer solution, please ?

i want to clip raster using vector layer. But the layer isn't detected/available in the dropdown option. i've set the CRS as well as the raster

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
