### ISSUE TITLE
CONFUSION MATRIX CONTAINS MUCH MORE VALIDATION POINTS IN CLASS 1 THAN VALIDATION POINTS EFFECTIVELY USED 

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#248]
Hello Lucas,
When creating a confusion matrix with the precision tool, the resulting confusion matrix contains too many points in class 1. In the example below, i worked with 8 validation pixels (8 pixels). And you can see that class 1 in confusion matrix (pixel count) contains a big number of points.
The same problem was observed on various computers of my students. 
Could you correct that? 
Best regards,
Antoine

![image](https://user-images.githubusercontent.com/44610746/208063602-7cbae508-2b51-4465-9f6b-30c6ef0189af.png)

![image](https://user-images.githubusercontent.com/44610746/208063513-1fe1ab72-2cf3-4d6b-842b-b9eb6ad3a902.png)

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , the issue is quite strange.
It seems that it used different input files. Please check that there are not layers with the same name loaded in QGIS, and try to perform the accuracy assessment in a new QGIS project.

**Comment by GITHUBAntoineDENIS** [comment]
Hello Lucas @semiautomaticgit ,
I tried in a new project with a single image in the project, and I got NO PROBLEM anymore.
I have no time currently to try to reproduce the error. So I think we can close this post.
Best regards,
Antoine

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , thank you very much for your feedback.
Of course please reopen this in case of errors.
Best regards!
