### ISSUE TITLE
Maximum likelihood algorithm not giving as good accuracy as expected?? 

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#249]
Hello Lucas,
Here is not really a bug, but a suspicion of a possible error in the maximum likelihood classification algorithm. Often me and my students observed that the max likelihood algorithm is giving way far less good classification accuracy than nearest neighboor algorithm. While I had the impression that the max likelihood should in theory perform better, or at least not giving very inaccurate classification. 
So maybe it would be interesting to check the max likelihood algorithm implementation in SCP. I have no time to make a real test with for example a comparison with another software like arcgis, sorry. 
Best regards,
Antoine

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , the algorithm implementation has not changed, so I don't think there are algorithm issues.  I think accuracy is related to the spectral distances of the ROIs.
Please calculate the spectral distances, in particular the Jeffries-Matusita Distance https://semiautomaticclassificationmanual.readthedocs.io/en/latest/spectral_signature_plot.html#spectral-distances-1
