### ISSUE TITLE
translation in french of one of the main menu

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#251]
Hello Lucas,

In the FRENCH version of SCP, the menu called "Télécharger des produits" , i think it would be better to call it 
"Téléchargement de produits" , like that you don't use a action verb, like for the other menu (kind of harmonization) .
Best regards,
ad

![image](https://user-images.githubusercontent.com/44610746/208067930-f2e9c552-5241-44f5-aec1-af9b2a2af147.png)

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , thank you very much for the suggestion. I agree it should be "Téléchargement de produits"

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
