### ISSUE TITLE
RT on Sentinel-2 yields "nan"

### ISSUE THREAD

**Issue by matthieuferryGM** [semiautomaticgit/SemiAutomaticClassificationPlugin#252]
Hi,
I am testing Tutorial 1 on several Sentinel-2 scenes to prepare a Lab Pactical for MSc students.
When converting to Reflectance, all is ok for bands 2/3/4 but fails for bands 5 and higher. Min values as displayed in QGIS are "nan" (or "-3,40282e+38"). Max values seem ok. This happens on freshly downloaded images (through SCP or directly) while provided S2 samples appear fine.

Thanks for helping,
Matthieu

Edit: this only happens when clipping first as in the tutorial. The issue doesn't rise when downloading with the "Pre-process images" option checked.

**Comment by semiautomaticgit** [comment]
Hello @matthieuferryGM ,
thank you for reporting this.
It seems an issue related to NoData values. 
However, if you stretch the raster values using QGIS layer style options, you should display the images correctly.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
