### ISSUE TITLE
LANDSAT IMAGES DO NOT DOWNLOAD WITH SCP: no image found. Try a lerger area

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#255]
Hello Lucas,
The Landsat images do not download with the SCP plugin. Confer image.
Test with landsat 8-9, on Corse and Sardaigne 2022-2023.
Best regards,
Antoine 
![image](https://user-images.githubusercontent.com/44610746/224933995-161a63f1-ff9f-4a7c-a312-11e946601e72.png)
![image](https://user-images.githubusercontent.com/44610746/224934409-c58a0bcf-2c50-420b-b080-670a1a8575a5.png)

**Comment by hrdrckx** [comment]
My colleagues and I are also experiencing this.  The issue persists no matter how large the area.

**Comment by semiautomaticgit** [comment]
Hello, it is an issue related to the download service. It will be solved in the next version of the plugin, which should be released in October 2023

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
