### ISSUE TITLE
Band set and pan-sharpening issue

### ISSUE THREAD

**Issue by Ohtwoniner** [semiautomaticgit/SemiAutomaticClassificationPlugin#26]
I'm analyzing Landsat-8 images and after converting the raw data to reflectance, I wanted to create a stacked raster image using Band Set for land cover classification. It worked fine when I used the simple reflectance bands, but when I tried using the pan-sharpened bands, the result was only a big black square, as if the whole image was nodata. _(note: the individual bands rendered properly in QGIS)_
 I checked the manual and the tutorials, but didn't find anything helpful. Since I'm quite the beginner in remote sensing and image processing, it's likely that I missed a setting or a parameter, so I would really appreciate any help with this issue.

**Comment by semiautomaticgit** [comment]
Thank you for reporting this. I'll look into it.
You can try with a different image. Also, check the images have the same pixel size.

**Comment by semiautomaticgit** [comment]
It should be fixed in version 6.
Please reopen this if you get the same error.
