### ISSUE TITLE
Calculating Accuracy Assesment  Problem

### ISSUE THREAD

**Issue by christian-ty** [semiautomaticgit/SemiAutomaticClassificationPlugin#262]
I am trying to do an accuracy assessment but  I am always getting the same errors.
[Qgis_Accuracy Assesment.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/11303690/Qgis_Accuracy.Assesment.txt)

**Comment by semiautomaticgit** [comment]
Hello @christian-ty ,
unfortunately the log file doesn't include any clues about the error.

Please check that input data have the same coordinate reference system and spatial resolution.
Also, you could check that the two input files have the same range of values.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
