### ISSUE TITLE
Empty classification report using the tutorial material (macOS)

### ISSUE THREAD

**Issue by andreatitolo** [semiautomaticgit/SemiAutomaticClassificationPlugin#266]
Hi! first of all thank you for this plugin :)

I am having an issue at the beginning of the classification accuracy process. When I follow [this guide](https://fromgistors.blogspot.com/2019/09/Accuracy-Assessment-of-Land-Cover-Classification.html) I try to do the classification report as described in point 1, but I got an empty file and empty classification report. The SCP log does not show any error. I downloaded the reclassified data from the link provided in the guide.

The first time I tried, python crashed and I got an error, but the following tries no error at all. I am attaching the python log file [here](https://drop.infini.fr/r/dUb_BxQemC#JumTu8epRQ4s9TgrZEI2/+GFkkS12vasAvp8/22sG6s=). I tried to change the python path to another one, but same results.

**Comment by semiautomaticgit** [comment]
Hi @andreatitolo , you are very welcome!

About your issue, it is related to the plugin installation in macOS.
You can try to follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
