### ISSUE TITLE
SCP downloading the wrong Sentinel file

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#269]
I'm on SCP v. 7.10.11 on QGIS 3.26.3.  I can search and find Sentinel-2 products via Copernicus, but the file that is downloading is not the one I selected and clicked "run" on.  I am attaching a screenshot where you can see the download, and the selected image.  Note that I want L2A products (by the way, I'd strongly recommend making surface reflectance products the default for just about any use).  

![scp_download_error](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/730189/30959ecd-0ddd-4018-93d5-f68c74143628)

**Comment by semiautomaticgit** [comment]
Hello, the tool doesn't download the selected image, but the ones loaded in QGIS as preview, or the whole table content as option
