### ISSUE TITLE
can't find satellite imagery

### ISSUE THREAD

**Issue by chascshin** [semiautomaticgit/SemiAutomaticClassificationPlugin#272]
The search for Sentinel 2 data has ceased. After entering the parameters and clicking on the search, the result window remains empty.

**Comment by semiautomaticgit** [comment]
Hello, please use the option to use the alternative search for Sentinel-2.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
