### ISSUE TITLE
Hello @semiautomaticgit ,

### ISSUE THREAD

**Issue by farhan7861991** [semiautomaticgit/SemiAutomaticClassificationPlugin#273]
Hello @semiautomaticgit ,

I am trying to use post processing options but i am unable to get the list of raster images in the tab what should i do i have refresh many times the tab but the plugin is unable to recognize the raster clasified files in accuracy assesment and classification report.
 
 I have tried using different raster images but unable to solve the problem but on the other side the vector files are recognized by the plugin kindly help me with this issue

**Comment by semiautomaticgit** [comment]
Hello @farhan7861991 , it could be an issue related to input data.
Please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
