### ISSUE TITLE
'Singleband gray' render where 'No-Data'

### ISSUE THREAD

**Issue by shapley** [semiautomaticgit/SemiAutomaticClassificationPlugin#275]
Hi,

Some bands are imported with a 'Min' value of '-3.40282e+38' (No-Data). If I change the value in QGIS Properties... > Symbology to '0.0001' the band is displayed. My question is whether this is a QGIS 'no value' symbol error and if so is this the correct action to take to give a min/max values to the imported bands (sentinel-2) in my case or should I re-download again?

![nodata](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/7022885/6f0f37b9-fb77-49bf-81f2-5c4602552b65)

![nodata2](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/7022885/779ea771-ab69-4fff-ad2a-193bb71b9082)

**Comment by semiautomaticgit** [comment]
Hi @shapley ,
it is an issue related to the NoData value of the raster. It is correct to set the minimum value for the visualization.
It shouldn't affect classifications however.

**Comment by shapley** [comment]
Thank you for explaining that.
