### ISSUE TITLE
Atmospheric correction output - multiband image not created

### ISSUE THREAD

**Issue by leoleo-1** [semiautomaticgit/SemiAutomaticClassificationPlugin#279]
Hello,

I have been trying to apply DOS1 atmospheric correction to a set of 6 Landsat images. I do this by running:
SAC Plugin -> Preprocessing -> load images -> tick the box for DOS1 atmospheric correction -> define directories -> run.

The output are a number of new layers which are exactly the same as the initial satellite image raster layers. In addition, no 'atmospherically corrected' multiband (stacked) layer is created. To verify this, no multiband image appears in the 'Band set' menu of the SAC Plugin.

Any idea why this is happening? 

My software: MacOS Ventura v. 13.5
QGIS version: 3.28.9-Firenze

Thanks a lot in advance!

Best,
Leonardos

**Comment by semiautomaticgit** [comment]
Hello,
it is likely an installation issue of the plugin in MacOS.
You can try to follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os

In October a new version of the plugin will be released which should solve this installation issues.
Best

**Comment by leoleo-1** [comment]
Okay, thanks for the info!

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
