### ISSUE TITLE
Calibration to radiance (not reflectance) option?

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#283]
Hi there!  I was wondering if there is an easy way short of manual band calcs to use the gain/offsets from e.g. Landsat to calculate the radiance image, not the reflectance image.

**Comment by semiautomaticgit** [comment]
Hi @jgrn307 , unfortunately at the moment there is not an easy way, but I'll think about adding this option
