### ISSUE TITLE
Non-drive mapped paths in Windows causing errors

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#284]
If I'm making a band set -> virtual raster, and the .tif files are on a path that is something like //file.somewhere.edu/somepath I'm finding that SCP will shoot a python error and I'll have to restart QGIS.  However, if there is a drive mapping that is the same as this, e.g. Z://somepath is the same directory as //file.somewhere/edu/somepath, the path that uses Z: works fine.  We've confirmed this a few times (with the fix).

**Comment by semiautomaticgit** [comment]
Hi, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
I'll look into this.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
