### ISSUE TITLE
How to contribute/add wavelength quick settings

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#285]
Both for the community but also locally, is there a way for us to contribute to different wavelength quick settings, e.g. Landsat 9?  Are they hardcoded in some file?  Can we (as your user community) help with this?

**Comment by semiautomaticgit** [comment]
Hi, the wavelengths are hardcoded in the source file.
However, with the new version 8 of SCP (to be released in October) it will be possible to load csv files with custom wavelength values.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Thank you!
