### ISSUE TITLE
Rename the bands by the wavelength

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#286]
One thing we're running into that's confusing is after you create a bandset, even with the correct wavelength settings, there isn't an easy way to see the wavelengths associated with the bands in the QGIS layer.  Would you consider renaming the bands once the bandsets have been made to be the wavelengths (if available)?  https://gis.stackexchange.com/questions/62005/how-to-rename-the-band-names-of-a-layer-stack shows one way to approach the problem using the .aux.xmls.  

Related: is there a way to store the wavelengths in the bandset's metadata (virtual or otherwise)?  These could be used by other programs e.g. the Temporal/Spectral Profile tool if so.

**Comment by semiautomaticgit** [comment]
Hi, thank you for your comments.
I'll try to include the wavelength information in the virtual raster of the band set.

> Related: is there a way to store the wavelengths in the band set's metadata (virtual or otherwise)? These could be used by other programs e.g. the Temporal/Spectral Profile tool if so.

The wavelengths are stored in the bands et. It is possible to export the band set as xml file, but I don't know if other programs can read it.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Thank you!
