### ISSUE TITLE
scp GUI problem

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#290]
Hello,
You can see in the gui below a code line in the gray line below

![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/f435d9c5-82a3-458f-8b08-ca0afa82a192)

**Comment by semiautomaticgit** [comment]
Thank you for reporting this.
I think it is related to the translation file.

**Comment by semiautomaticgit** [comment]
fixed in 8.0.3
