### ISSUE TITLE
semi-automatic-classification plugin 8.0.3

### ISSUE THREAD

**Issue by LustigeGarnele** [semiautomaticgit/SemiAutomaticClassificationPlugin#292]
Hello,

I don't find the function "apply mask" like in the versions before. How do I apply a Band set with a shape-file in this scp-version?

Thank you

**Comment by semiautomaticgit** [comment]
Hello @LustigeGarnele , you can use the tool Masking bands in Preprocessing
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/masking_bands_tab.html

About the shapefile, you can use this tool 
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/classification_to_vector_tab.html
