### ISSUE TITLE
Point outside band set or band set not defined

### ISSUE THREAD

**Issue by jgrn307** [semiautomaticgit/SemiAutomaticClassificationPlugin#293]
I'm trying to make an ROI (either via a point or polygon) -- I've created a new Training input, but when I go to use the Create a ROI polygon or Activate ROI pointer, I get a "Point outside band set or band set not defined" error.  See screenshot below.  Note that the Virtual Band Set 1 has been created and is visualized.  Any ideas what is going on?  Did I miss a step?  When I make an ROI, how do I set which band set it should be using?

![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/730189/6830e655-adb6-40e0-a00f-4774f6c9922e)

**Comment by jgrn307** [comment]
Here is the image files: https://drive.google.com/drive/folders/1T-cuo2Gt3936q55Fao-99I0MIpwrLOuW?usp=sharing

They are the classic "Cuprite, NV" aviris subset from the ENVI tutorial.  The csv is the wavelength file for importing the correct wavelengths.

The only weird thing I've noticed so far is that the imagery has no CRS/geographic information.

**Comment by jgrn307** [comment]
Unfortunately, that didn't solve it.  I've added a referenced GeoTIFF to the above Google Drive folder (same file as before, but I defined a CRS and bounding box) and I am getting exactly the same error.  Thoughts?

**Comment by jgrn307** [comment]
It's possible I am not 100% sure how this works -- how do I create an ROI that is connected to a specific band set/virtual raster?  Do I have to set some "active" bandset for this to work?  I loaded up the data in the bandset dialog, and then used the RGB to put the layer into the QGIS panel, then I started using the ROI tool.  What is the correct process to go from bandset -> visualization -> ROI?

**Comment by semiautomaticgit** [comment]
> Unfortunately, that didn't solve it. I've added a georeferenced GeoTIFF to the above Google Drive folder (same file as before, but I defined a CRS and bounding box) and I am getting exactly the same error. Thoughts?
> 
> Direct link to the GeoTIFF: https://drive.google.com/file/d/1tsEnkhj6Z5Ac8PjKyCQW1yBi-6H-uC1I/view?usp=sharing and the wavelength file: https://drive.google.com/file/d/15g3F28ZoH5NQMTaGCvWpgyEVZbUj_VQ3/view?usp=sharing

Thank you for the files.
However, you can see from the coordinates (e.g. 388, 358) that the file is not correctly georeferenced.
So, the point warning is correct. So I'm closing this issue for the moment.
Of course if you have other issues with correctly georeferenced images please reopen the ticket.

>It's possible I am not 100% sure how this works -- how do I create an ROI that is connected to a specific band set/virtual raster? Do I have to set some "active" bandset for this to work? I loaded up the data in the bandset dialog, and then used the RGB to put the layer into the QGIS panel, then I started using the ROI tool. What is the correct process to go from bandset -> visualization -> ROI?

The workflow is:

1. band set creation
2. set the band set as active band set (if other band sets are present)
3. create a training input in the SCP Dock
4. load the RGB composite of the band set (optional, not required for ROI creation)
