### ISSUE TITLE
Search for landsat images give no result

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#297]
Hello,
The search with scp for landsat images gives no result and error message.
My login to https://urs.earthdata.nasa.gov/ is working well however.
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/e28ca1ea-8753-4218-a789-af3502397405)
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/ce8fed27-89fa-4731-8382-b5c04f0988f2)
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/37f7619b-1612-47c0-a855-5b4d5f1a76ff)

ERROR MESSAGE : SCP: HTTP Error 400: Bad Request; url:https://cmr.earthdata.nasa.gov/search/granules.echo10?polygon[]=4.0,45.0,4.0,46.0,6.0,46.0,6.0,45.0,4.0,45.0&echo_collection_id=C2021957657-LPCLOUD&temporal=2022-05-05%2C2023-10-12T23%3A59%3A59.000Z&sort_key%5B%5D=-start_date&page_size=20&page_num=1&pretty=true

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , 
the UL point you entered has Y coordinate lower than LR Y coordinate, while it should be the opposite.
You should invert such as UL 4 46 and LR 6 45
