### ISSUE TITLE
pop up text of scp button with code visible

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#300]
Hello, many button havec a "code pop up text" rather than a propoer text: confer image
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/8a8f3807-d23a-4fc5-bc8b-11b61cb1ec17)

**Comment by semiautomaticgit** [comment]
Thank you very much @GITHUBAntoineDENIS . 
The issue is related to the translation file, which was created with the previous version of SCP.
For the moment I think it is better to remove the localization files, as there are incoherent translations, and add the files only when completely translated.
