### ISSUE TITLE
Remotior Sensus Missing

### ISSUE THREAD

**Issue by CesarPalomino** [semiautomaticgit/SemiAutomaticClassificationPlugin#301]
I'm upgrate few minutes ago the pluggin, and QGIs send a notification  "Install the remotior-sensus library" (In the older version of this plugin this library did´nt generate problems).

![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/60803729/fe357e07-0dc3-40fa-9cfc-2c4e88cfcb51)

**Comment by kmtk49** [comment]
I had same problem. does not work when re-installed

**Comment by TysonDude** [comment]
I suggest to install the older version 7. Its happening to a lot of users. The new version is either not working or keeps crashing QGIS. So, its better to install the older version 7. But make sure to uninstall & clear all the files of QGIS. (You can delete plugin files from %appdata%) 
Then, install again with version 7. 
(You can download it from https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/version/7.10.11/)

**Comment by kmtk49** [comment]
Older version ７ installed successfully. Thank for prompt reply.

**Comment by semiautomaticgit** [comment]
> I suggest to install the older version 7. Its happening to a lot of users. The new version is either not working or keeps crashing QGIS. So, its better to install the older version 7. But make sure to uninstall & clear all the files of QGIS. (You can delete plugin files from %appdata%) Then, install again with version 7. (You can download it from https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/version/7.10.11/)

Thank you @TysonDude , but I recommend to install the new version 8 first, and only in case of issues install the version 7.


>I had same problem. does not work when re-installed

The new version of the plugin requires a few Python dependencies that must be installed. 
@kmtk49 the message means that  you need to install the required dependency Remotior Sensus.
To install the new version please follow these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html

**Comment by vcqgis07** [comment]
Thank you. I was also facing the same issue. It gets resolved now. Your suggestion worked. Thanks a lot.

**Comment by semiautomaticgit** [comment]
@vcqgis07 you are very welcome!

**Comment by semiautomaticgit** [comment]
I'm closing this as installation issues should be solved now.

**Comment by semiautomaticgit** [comment]
> Funcionó!!! muchas gracias.

You are very welcome!
