### ISSUE TITLE
UNABLE TO PROCESS FILE AT IMAGE CONVERSION

### ISSUE THREAD

**Issue by vhenriquezl** [semiautomaticgit/SemiAutomaticClassificationPlugin#304]
im trying to preprocess landsat 9 and it doesnt find the files.. PLEASE HELP

**Comment by semiautomaticgit** [comment]
Hello, please check that the metadata xml file is inside the image directory.

**Comment by vhenriquezl** [comment]
> Hello, please check that the metadata xml file is inside the image directory.

it is, and it still doesnt work

**Comment by semiautomaticgit** [comment]
please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by vhenriquezl** [comment]
> please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

INFO|2023-10-20T16:42:29.182|system_tools|get_system_info|38|system: Windows; 64bit: True; n_processes: 2; ram: 10; temp.dir: C:\Users\valeh\AppData\Local\Temp\remotior_sensus_102015z7894h
INFO|2023-10-20T16:43:11.567|image_conversion_tab|populate_table|62|populate_table input_path: D:/tesis/calculo NDVI/2023/20230109; metadata_file_path: None
INFO|2023-10-20T16:43:16.260|image_conversion_tab|populate_table|62|populate_table input_path: D:/tesis/calculo NDVI/2023/20230109; metadata_file_path: D:/tesis/calculo NDVI/2023/20230109/LC08_L2SP_001074_20230109_20230124_02_T1_MTL.txt
INFO|2023-10-20T16:43:19.285|preprocess_products|perform_preprocess|137|start
ERROR|2023-10-20T16:43:19.519|multiprocess_manager|find_minimum_dn|1792|unable to process
ERROR|2023-10-20T16:43:19.733|preprocess_products|perform_preprocess|570|unable to process files
INFO|2023-10-20T16:43:45.454|session|set|405|n_processes: 2; ram: 10; temp.dir: C:\Users\valeh\AppData\Local\Temp\remotior_sensus_102015z7894h

**Comment by semiautomaticgit** [comment]
Thank you for the log file. 
It seems that you selected the file LC08_L2SP_001074_20230109_20230124_02_T1_MTL.txt as metadata.
You should select the metadata .xml file or if this file is already in the directory you can also skip the selection of the metadata file.
