### ISSUE TITLE
SCP plugin python library error

### ISSUE THREAD

**Issue by MusaEmir** [semiautomaticgit/SemiAutomaticClassificationPlugin#305]
Hello,
When i try to upload SCP plugin i take this error 
![resim_2023-10-22_174951996](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/35701530/80f82cd2-7b7e-41f1-bab5-97f60b2227b1)
Could you help me about that

**Comment by semiautomaticgit** [comment]
Hello @MusaEmir , please follow these installation steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html

**Comment by MusaEmir** [comment]
Thank you brother ! Have a nice day

**Comment by semiautomaticgit** [comment]
You are very welcome!
