### ISSUE TITLE
Unsupervised learning in SCP 8

### ISSUE THREAD

**Issue by gbouzill** [semiautomaticgit/SemiAutomaticClassificationPlugin#307]
Hello, 

I just switched to SCP 8 and I am unable to find K-mean and Isodata algorithms in this version.
Are they still available ? If not, is it planned to be implemented soon ?

Thank you in advance.

**Comment by semiautomaticgit** [comment]
Hello @gbouzill , yes, unfortunately clustering is not available in version 8.
It will be probably added the next year.

**Comment by micheliam** [comment]
hey i have the same problem, would it be possible to somehow to backdate to version 7 or 6 while I have version 8 now?

**Comment by semiautomaticgit** [comment]
> hey i have the same problem, would it be possible to somehow to backdate to version 7 or 6 while I have version 8 now?

Hello @micheliam, yes you can install version 7 following this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#can-i-use-the-previous-version-7-of-scp

**Comment by corgne** [comment]
Hello,

I have tried also to apply unsupervised classification as K-means or Isodata with no success with the version 8.2.2. Do you plan to integrate it this year ? it is very useful to help students to understand the basics of image classification.
Thanks a lot and congratulations for your plugin, fantastic tool for remote sensing applications !

**Comment by semiautomaticgit** [comment]
Hello @corgne ,

> I have tried also to apply unsupervised classification as K-means or Isodata with no success with the version 8.2.2. Do you plan to integrate it this year ? it is very useful to help students to understand the basics of image classification. 

Yes, I plan to integrate unsupervised classification but unfortunately I can't assure this year.

>Thanks a lot and congratulations for your plugin, fantastic tool for remote sensing applications !

You are very welcome! I'm glad you appreciate my work.

**Comment by semiautomaticgit** [comment]
Hello, I close this because clustering (K-means) has been implemented in SCP 8.3
