### ISSUE TITLE
SCP won't read bands

### ISSUE THREAD

**Issue by Bronzeager** [semiautomaticgit/SemiAutomaticClassificationPlugin#315]
Hello.

I've been encountering an issue while trying to perform DOS1 correction on Landsat 5 and Landsat 8 images using the QGIS SemiAutomaticClassificationPlugin. I've tried this on both Bialoweza and Firenze versions of QGIS. The plugin is not recognizing any bands in the specified file. This issue started after the recent update of the plugin.

Before the update, everything worked smoothly. However, post-update, I received errors indicating the need for additional Python modules, including Remotior Sensus and another module, which I then installed manually. This resolved the initial error, but the issue with the plugin not detecting bands in the file persists.

I have tested this on multiple computers with the same outcome. Notably, I was able to create a bandset, so the data itself seems to be fine. It appears to be a specific issue with the plugin's functionality post-update.

Any assistance or suggestions to resolve this would be greatly appreciated.

Thank you.

![bilde](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/150611275/ed64b54f-c30d-4bf6-88c9-d25b82b40654)

**Comment by semiautomaticgit** [comment]
Hello @Bronzeager ,

thank you for reporting this.

> I've been encountering an issue while trying to perform DOS1 correction on Landsat 5 and Landsat 8 images using the QGIS SemiAutomaticClassificationPlugin.

What is the source collection of Landsat images?
Also, could you check if the metadata xml file is inside the image directory?

Also, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by MartyC-137** [comment]
I was having the same issue with clipped Landsat8 images from [Earth Explorer](https://earthexplorer.usgs.gov). 

Moving the `LC08_..._MTL.xml` file into the same directory as the clipped images resolved the issue for me.

**Comment by SwathiGit1** [comment]
Hi,

I face the same issue. The 'Clip Raster Bands' under 'Pre-processing' works as expected. However, when I click the 'Image Conversion', my bands aren't selected. I tried both ways: by manually selecting the metadata(_MTL.txt) and by leaving it blank. The same issue persists. 
Any help is greatly appreciated, thank you.
![Screenshot 2024-05-31 125831](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/60208238/437698cf-644d-481f-9797-8b62297dfd1a)

**Comment by semiautomaticgit** [comment]
> Hi,
> 
> I face the same issue. The 'Clip Raster Bands' under 'Pre-processing' works as expected. However, when I click the 'Image Conversion', my bands aren't selected. I tried both ways: by manually selecting the metadata(_MTL.txt) and by leaving it blank. The same issue persists. Any help is greatly appreciated, thank you. ![Screenshot 2024-05-31 125831](https://private-user-images.githubusercontent.com/60208238/335568686-437698cf-644d-481f-9797-8b62297dfd1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzYxMDIsIm5iZiI6MTcxNzkzNTgwMiwicGF0aCI6Ii82MDIwODIzOC8zMzU1Njg2ODYtNDM3Njk4Y2YtNjQ0ZC00ODFmLTk3OTctOGI2MjI5N2RmZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEyMjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZGFkYTBhNWM1NjBkNzk0YzJlNjVhYmMwNTc4NGI1YjE1MDNjODE3YmZkODQ2ZjhkMTY5MWRkNTgwZGNhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9mzlWEkO_ulbyXQDLwUaSgdC4DYB7kzDRcoiFXt5EU)

Hi @SwathiGit1 , you should select the .xml metadata file.

**Comment by SwathiGit1** [comment]
Hi @semiautomaticgit 

Thank you very much, it now works like a charm 👍 
In case there are others like me, who have a metadata TXT (.txt) file but don't have a metadata XML (.xml) file can get their txt file converted to xml. And one way to do that is [here](https://github.com/landscapelc/Landsat8_to_xml/tree/main)

**Comment by semiautomaticgit** [comment]
> Hi @semiautomaticgit
> 
> Thank you very much, it now works like a charm 👍 In case there are others like me, who have a metadata TXT (.txt) file but don't have a metadata XML (.xml) file can get their txt file converted to xml. And one way to do that is [here](https://github.com/landscapelc/Landsat8_to_xml/tree/main)

Hi @SwathiGit1 , thank you for your feedback and the suggestion to convert txt to xml file.
