### ISSUE TITLE
Installation Trouble with SCP Plugin Due to Possible Package Conflicts. 

### ISSUE THREAD

**Issue by SHAYKE80** [semiautomaticgit/SemiAutomaticClassificationPlugin#317]
Issue Title: Installation Trouble with SCP Plugin Due to Possible Package Conflicts
Description:
I've encountered a problem during the installation of the SCP (Semi-Automatic Classification Plugin) in QGIS, which seems to be related to package conflicts. After installing the required Python packages (remotior-sensus, torch, and scikit-learn), I encountered errors when trying to use the SCP plugin.

Steps to Reproduce:

Install remotior-sensus, torch, and scikit-learn in the QGIS Python environment.
Install the SCP plugin in QGIS.
Attempt to use the SCP plugin.
Expected Behavior:
The SCP plugin should install without errors and function correctly.

Actual Behavior:
Encountered errors during the use of the SCP plugin. The errors are as follows:
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/96472281/b4a6088c-376d-4bba-af21-2d6b22a43714)

and,
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/96472281/e3bd75ff-b081-44e7-97b9-54940e36c3c0)

Environment:

QGIS Version: [3.28.10]
SCP Plugin Version: [8.1.3]
Operating System: [Windows 10]

**Comment by semiautomaticgit** [comment]
Hello @SHAYKE80 ,
it could be a NumPy issue, please try to run 
`pip3 install --upgrade numpy`

**Comment by SHAYKE80** [comment]
I uninstalled a plugin that needed a numpy version of 1.16, upgraded numpy and now SCP is installed.

**Comment by semiautomaticgit** [comment]
thank you for your feedback
