### ISSUE TITLE
SCP does not automatically load the output or play the sound when it finishes processing

### ISSUE THREAD

**Issue by claudioasn** [semiautomaticgit/SemiAutomaticClassificationPlugin#318]
Hello, in previous versions SCP automatically loaded the results of a particular processing (e.g. PCA). As of version 8 this is not happening. Is this the case?

Also, the processing completion sound no longer appears, even though this option is activated in the settings.

**Comment by semiautomaticgit** [comment]
Hello @claudioasn 

> Hello, in previous versions SCP automatically loaded the results of a particular processing (e.g. PCA). As of version 8 this is not happening. Is this the case?

PCA are actually loaded in QGIS. Probably you mean the preprocessed bands, that are no longer loaded in QGIS because band set creation doesn't require loaded bands anymore.

> Also, the processing completion sound no longer appears, even though this option is activated in the settings.

Thank you for reporting this. It is fixed in version 8.1.4. Please update both SCP and Remotior Sensus

**Comment by semiautomaticgit** [comment]
> Hi @semiautomaticgit
> 
> > Thank you for reporting this. It is fixed in version 8.1.4. Please update both SCP and Remotior Sensus
> 
> I confirm that the sound is working again.

Thank you for your feedback!
