### ISSUE TITLE
classification output and ROI files are added twice in the qgis layers panel

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#322]
Hello,
When creating a classification output image, or a temporary ROI files,
they are added twice in the qgis layers panel : there are 2 layers in the qgis layers pannel. each can be checked /unchecked for controling visibility

Maybe this is because i was working with layers subgroup in qgis layers pannel : one layer is at the tope of the pannel and one in a subgroup of layers.

This is not convenient to get 2 layers for in fact one information. 

Best regards,
Antoine

**Comment by GITHUBAntoineDENIS** [comment]
Hello,
In the qgis layers (COUCHES in french) panel, you can create groups in order to organise your layers in different groups that are more easily manageable (moving, visibility, etc). Confer image for the location of that button.
In my project I have different groups : one is called "TEST 21 novembre" : confer image.
When producing a classification, the classification image was automatically added in that group AND outsides of the groups I have. You can see on the image below that the file "CLASSIF 1" (the classification image)  is present twice in the layers pannel. 
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/517c5393-d0a0-4f77-bbbc-0f944dd4ad6f)


![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/44610746/2a3c950a-5ca8-433d-8e3b-0d6a4fdf0e06)

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , I have fixed this in version 8.1.5.
Thank you for reporting the issue.

**Comment by GITHUBAntoineDENIS** [comment]
OK thank you it works fine now ! :-) 👍
