### ISSUE TITLE
SCP 7: Unsupervised Clustering: Error 6 Bands Missing

### ISSUE THREAD

**Issue by sharonmandipe** [semiautomaticgit/SemiAutomaticClassificationPlugin#323]
Whilst getting other people to run an unsupervised (ISODATA) classification in QGIS using the SCP (semi-automatic classification) plugin, several people obtained an error message labeled 'error 6: classification failed. It appears one or more of the band set are missing'

I initially thought this was because they hadn't saved the files for each band in the same file as the band stack file we were using for analysis, but this doesn't seem to be the case.

Others tried repeating the process of making the band stack: 
![KkC6Z](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/118908238/2e208183-9ff4-47ab-b946-d256cb76f3bc)

As you can see above, bands 1 to 7 of Landsat data are input to band set 1 for the formation of a stack of bands. When this stack of bands is used to generate the unsupervised classification (clustering), the error message appears..
![FQfpR](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/118908238/15b937c7-61a7-483d-adbf-464cfa2f897d)

All of the relevant bands are still present in the layout view of the GIS (they have not been deleted and are located in the same folder as the QGIS project).

Has anybody encountered this problem before?

Thanks

**Comment by semiautomaticgit** [comment]
Hello @sharonmandipe , unfortunately it is an issue of the old version 7 of SCP.
You can try k-means which should be more stable.

Clustering will be probably added the next year to the version 8 of SCP.
