### ISSUE TITLE
Land Cover Change is missing in SCP's postprocessing

### ISSUE THREAD

**Issue by IshretShuchana** [semiautomaticgit/SemiAutomaticClassificationPlugin#324]
Hi,
From SCP's catalogue we can see there is a tool named 'Land Cover Change' and few more which you can find from the link below.  In my QGIS under postprocessing there is only 5 items are present. Items are named accuracy, classification report, cross classification, classification to vector, reclassification.   Would really appreciate your suggestion. Thanks.

https://semiautomaticclassificationmanual.readthedocs.io/ar/latest/landCoverChangeTab.html?highlight=Land%20cover%20change

**Comment by semiautomaticgit** [comment]
Hi @IshretShuchana ,

the land cover change function is now integrated in the "cross classification" tool which performs the same calculation between two rasters.
Please read https://semiautomaticclassificationmanual.readthedocs.io/en/latest/cross_classification_tab.html

**Comment by IshretShuchana** [comment]
That is great. Many thanks.
