### ISSUE TITLE
SCP FRENCH interface?

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#326]
Hello,
Is there a way to get the french interface of SCP? 
It would be nice if we can set it through the settings > interface.
A student tol me she got a part of the interface in french. On my side, everything is in english (my computer is in english)
Best regards,
ad

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , the interface translation is not available at the moment, and the French translation is incomplete.
Of course in the future it will be available.
Probably the student is using the previous version 7 of SCP.

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS ,
the interface localization is now available in SCP version 8.3.
