### ISSUE TITLE
Information [4]: Select a raster; raster is not loaded

### ISSUE THREAD

**Issue by gteduarte16** [semiautomaticgit/SemiAutomaticClassificationPlugin#327]
1. Create a band set, successfully (But when trying to create a stack bands, nothing shows in the output folder)
2. Attempt to save a training input set and get the following message: Information [4]: Select a raster; raster is not loaded

**Comment by semiautomaticgit** [comment]
I'm closing this. Of course please reopen this ticket if it is still relevant.
