### ISSUE TITLE
Contributing to SCP

### ISSUE THREAD

**Issue by jgrocha** [semiautomaticgit/SemiAutomaticClassificationPlugin#33]
Hi,
The SCP is **awesome**! I would like to contribute to it. I will do my best, but I need help. I'm not a Python programmer, neither a Remote Sensing expert.
I didn't find a developer guide and `make deploy` didn't work for me out of the box.
So I decided to create a very simple `DEVELOPMENT.md` file and I fixed the `Makefile` so others can start contributing more easily.
Does this make sense? I'll submit a Pull Request with my minor changes to the project.
Comments are welcome.

**Comment by semiautomaticgit** [comment]
Hi  Jorge Gustavo,
I'm glad that you appreciate SCP.
Thank you very much for your support! This is a very useful contribution.
Cheers
