### ISSUE TITLE
Python output error during supervised classification

### ISSUE THREAD

**Issue by Hueching0411** [semiautomaticgit/SemiAutomaticClassificationPlugin#330]
After I click 'RUN' and set the file location, the classification could not be run and the process keep fail. The following python error occurred and I do not understand the meaning.

2023-12-27T18:53:24     WARNING    Traceback (most recent call last):
              File "C:\Users/ching/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 143, in run_classification_action
              run_classifier()
              File "C:\Users/ching/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 487, in run_classifier
              if output is None:
             UnboundLocalError: local variable 'output' referenced before assignment

Could anyone help to solve this problem?

**Comment by semiautomaticgit** [comment]
Hello @Hueching0411 , thank you for reporting the issue.
Please update both SCP and Remotior Sensus. 
If you still get the same issue, please check the checkbox "Records detailed events in a log file" and copy the log file as described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by JoseRascon** [comment]
Hello, I get the following error when running a supervised classification (I'm trying to make a model and I can't)
Traceback (most recent call last):
  File "C:\Users/jrassan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 148, in save_classifier_action
    output = run_classifier(save_classifier=True)
  File "C:\Users/jrassan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 487, in run_classifier
    if output is None:
UnboundLocalError: local variable 'output' referenced before assignment

Just in case I also put the error that I get from the application in report error
INFO|2024-03-04T14:47:24.010|system_tools|get_system_info|38|system: Windows; 64bit: True; n_processes: 2; ram: 10; temp.dir: C:\Users\jrassan\AppData\Local\Temp\remotior_sensus_0304trf64cdn
INFO|2024-03-04T14:48:26.408|bandset_catalog|create|744|start
ERROR|2024-03-04T14:48:26.415|table_manager|create_band_table|1186|Python int too large to convert to C long; nodata: -9.223372036854776e+18
ERROR|2024-03-04T14:48:26.419|table_manager|create_band_table|1186|Python int too large to convert to C long; nodata: -9.223372036854776e+18
ERROR|2024-03-04T14:48:26.423|table_manager|create_band_table|1186|Python int too large to convert to C long; nodata: -9.223372036854776e+18
ERROR|2024-03-04T14:48:26.430|table_manager|create_band_table|1186|Python int too large to convert to C long; nodata: -9.223372036854776e+18
INFO|2024-03-04T14:48:26.430|bandset_catalog|create|927|end; file list: ['D:/AlgoritmoClasificado/Mayo2020.tif']
INFO|2024-03-04T14:48:38.596|scp_dock|open_signature_catalog_file|2465|open_signature_catalog_file: D:/AlgoritmoClasificado/Training.scpx
INFO|2024-03-04T14:49:03.413|classification_tab|run_classifier|193|run_classifier: D:/AlgoritmoClasificado/Modelo.rsmo.tif
INFO|2024-03-04T14:49:03.440|band_classification|band_classification|1235|start
ERROR|2024-03-04T14:49:16.633|classification_tab|run_classifier|485|boolean index did not match indexed array along dimension 0; dimension is 21261 but corresponding boolean dimension is 15
INFO|2024-03-04T14:50:25.505|session|set|405|n_processes: 2; ram: 10; temp.dir: C:\Users\jrassan\AppData\Local\Temp\remotior_sensus_0304trf64cdn

**Comment by varshithvn2** [comment]
I'm facing the same issue.

Maximum Likelihood works fine, But rest of the algorithm shows same error.
Random Forest has a different issue,
"RandomForestClassifier" Not Found

**Comment by semiautomaticgit** [comment]
Hello, it should be fixed in SCP version 8.3.
Please reopen a ticket in case it is still relevant.
