### ISSUE TITLE
DOS1 Correction

### ISSUE THREAD

**Issue by Jacobaslan12** [semiautomaticgit/SemiAutomaticClassificationPlugin#332]
Hi !!
I have a question.
When i try to run the conversion tool for reflectance and the DOS1 correction in Landsat 8 data.
The tool ddo the process, but when i try to deploy the result in RGB432
The result deploy in red color, not in RGB432.
How can i fix it?
Thank you for your time.

Best Regards,

Nieto Jacob

**Comment by semiautomaticgit** [comment]
Hi @Jacobaslan12 ,
it could be an issue with input data.
Moreover, I recommend downloading the Level 2 products that are already atmospherically corrected.

**Comment by semiautomaticgit** [comment]
Hi @Jacobaslan12 , 
I'm closing this, but please reopen if it is till relevant.
