### ISSUE TITLE
Files are not loaded while using image conversion option

### ISSUE THREAD

**Issue by Leendecode** [semiautomaticgit/SemiAutomaticClassificationPlugin#333]
I tried loading the data set from the directory and provided the meta data file but still no data is loaded in the bandset option and as a result I can't perform the preprocessing option for Landsat 8 imagery. Please help jow to resolve this.
<img width="669" alt="error" src="https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/155967330/c8d5920f-c825-4ebe-9942-07d505c59bc2">

**Comment by semiautomaticgit** [comment]
Hello, please update both SCP and Remotior Sensus. 
If you still get the same issue, please enable "Records detailed events in a log file" and copy the log file as described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
Hello, I think the issue was related to the selection of the wrong metadata file (.txt) instead of the .xml file.
I'm closing this, but if you still encounter this issue please reopen this ticket.
