### ISSUE TITLE
SCP Edit Toolbar is missing

### ISSUE THREAD

**Issue by shaheen-git** [semiautomaticgit/SemiAutomaticClassificationPlugin#334]
Hi,
After installing the SCP, I can not find the [SCP Edit Toolbar](https://semiautomaticclassificationmanual.readthedocs.io/ar/latest/toolbar_edit_raster.html). I can only see SCP Dock Panel and SCP Working Toolbar. Right click does not show SCP Edit toolbar option to be selected.

To make sure this is not related to my QGIS, I installed the latest version of QGIS on another PC and installed the SCP plugin. Still the same problem.

Any help on this?

Thanks!

**Comment by semiautomaticgit** [comment]
Hi @shaheen-git , 
the new version 8 has not implemented the Edit toolbar.
I'll try to add this function in the future.

**Comment by semiautomaticgit** [comment]
Hello @shaheen-git , the tool Edit raster has been added in SCP version 8.3
I don't include the toolbar anymore to avoid confusion in the QGIS toolbar, but you can use all the Edit options from the main interface.
