### ISSUE TITLE
Error 19

### ISSUE THREAD

**Issue by maragauna** [semiautomaticgit/SemiAutomaticClassificationPlugin#336]
I'm using the 7.0 version on qgis 3.28 because of the data this version provides, but it's not letting me upload point shapefiles to create the ROIs, an error 19 message appears when i try to upload points.
![Captura de pantalla (16)](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/157522412/b41cea09-c74b-4adb-b337-df9b6549d6bc)

**Comment by semiautomaticgit** [comment]
Hello @maragauna , you should check that vector file has the same coordinate reference system of the input band set. Unfortunately version 7 is not supported anymore.  You can try to install version 8.
