### ISSUE TITLE
Cross Classification doesn't work

### ISSUE THREAD

**Issue by gabrielassanuma** [semiautomaticgit/SemiAutomaticClassificationPlugin#344]
I am attempting to use the cross classification, but it seems that the plugin is not functioning according to the technical documentation. When selecting the two rasters and executing the algorithm, nothing happens, leaving QGIS static on this screen.

<img width="1521" alt="image" src="https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/104199523/01789611-f6c1-4fd9-9dea-aec0f1ee7075">

I've tried to reinstall, reboot, other rasters...
I'm on mac M3.
There is no Log's or Error's message. Tks

**Comment by semiautomaticgit** [comment]
Hello, please enable "Records detailed events in a log file" and copy the log file as described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
Hello, it should be fixed in SCP version 8.3.
Of course, please reopen this ticket in case you still get this error.
