### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by lelekieu** [semiautomaticgit/SemiAutomaticClassificationPlugin#345]
I've received this message when trying to install the plug in. 

> RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem. 

I used OSGEO4W to install the release candidate version (3.36), the LTR version (3.34) of QGIS, and the additional packages as guided in the documentation, i.e., Remotior Sensus, scikit-learn and PyTorch. The plug in was failed to install on both QGIS versions. 

Anyone know the possible solutions for that? Thank you!

**Comment by semiautomaticgit** [comment]
Hello @lelekieu , it is not a plugin issue. It is something related to numpy compiled version.
Generally, you should uninstall OSGEO4W and then reinstall it.
