### ISSUE TITLE
Pre-processing not working after update

### ISSUE THREAD

**Issue by carlosobu** [semiautomaticgit/SemiAutomaticClassificationPlugin#348]
Updated SCP after half a year without using it and now when I preprocess ASTER, LANDSAT and SENTINEL images the process runs fine, exports the RT_ images but they are empty, all no data. Tried reinstalling the plugin but the problem persists (running QGIS 3.36 on Ubuntu 18, Python 3.7). Tried to install in a different OS but now SCP doesn't have the separate ASTER, LANDSAT and SENTINEL menus. How can I fix this?

**Comment by semiautomaticgit** [comment]
Hello @carlosobu , 

the new SCP version 8 includes the tool [Image conversion](https://semiautomaticclassificationmanual.readthedocs.io/en/latest/image_conversion_tab.html) for converting all the products to reflectance (at the moment only Landsat and Sentinel-2).
If you need to preprocess ASTER images  you can install the previous version 7 following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#can-i-use-the-previous-version-7-of-scp

**Comment by carlosobu** [comment]
When trying to install scp 8.2.2 (either via qgis plugin manager or via .zip file), by the end of the process the SCP dock or toolbars don't show up anywhere in any menu, and I get the following error message:

'Semi-Automatic Classification Plugin: future feature annotations is not defined (configurations.py line 22)'

SCP 7.10.11 will install fine via the .zip file, but still the processed images are empty like mentioned in the original comment. Also when testing for dependencies I get the following fails:
-SNAP subprocess: Fail
-Python multiprocess: Fail
-GDAL multiprocess: Fail

Is this a Linux os issue?

**Comment by semiautomaticgit** [comment]
> When trying to install scp 8.2.2 (either via qgis plugin manager or via .zip file), by the end of the process the SCP dock or toolbars don't show up anywhere in any menu, and I get the following error message:
> 
> 'Semi-Automatic Classification Plugin: future feature annotations is not defined (configurations.py line 22)'
> 
> SCP 7.10.11 will install fine via the .zip file, but still the processed images are empty like mentioned in the original comment. Also when testing for dependencies I get the following fails: -SNAP subprocess: Fail -Python multiprocess: Fail -GDAL multiprocess: Fail
> 
> Is this a Linux os issue?

I think it is a system specific issue related to plugin dependencies. Please try to uninstall QGIS and reinstall it completely.
