### ISSUE TITLE
Search parameter for Download Products not working.

### ISSUE THREAD

**Issue by dj-spatial** [semiautomaticgit/SemiAutomaticClassificationPlugin#349]
When I try to download satellite products and click "+" button, Upper Left coordinate works fine. However, Lower right(LR) coordinate doesn't work. No orange bounding box appears and LR X, Y  are still empty.
I've tried current QGIS  LTR 3.34 and previous 3.28 in Win 10 and Win 11. It doesn't work in any case.

![screem shot](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/162799399/b80c5887-e839-4e3c-b9e5-def4e4ee1385)

**Comment by semiautomaticgit** [comment]
Hello @dj-spatial , could you please check if you used the right click in the map for defining the LR point?

**Comment by dj-spatial** [comment]
It works. Thanks!

**Comment by semiautomaticgit** [comment]
You are welcome!
