### ISSUE TITLE
Miss processing Clustering in Version 8.2.2

### ISSUE THREAD

**Issue by dimas73** [semiautomaticgit/SemiAutomaticClassificationPlugin#351]
Why Miss the Clustering process in version 8.2.2?
can you tell I can do a clusterinf process od bans set in version 8 o how can i download previous version 7 where this process was active?
greeting

**Comment by semiautomaticgit** [comment]
Hello, clustering is not available in version 8 (it will be added in the future). In the meantime, you can install the previous version 7 following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#can-i-use-the-previous-version-7-of-scp
