### ISSUE TITLE
Problem with Landsat photos

### ISSUE THREAD

**Issue by hukjhnilh** [semiautomaticgit/SemiAutomaticClassificationPlugin#352]
Hi,
I downloaded photos from EOSDA LandViewer, from Landsat-7, I wanted to classify
I downloaded photos from EOSDA LandViewer, from the Landast-7 satellite, and I wanted to classify them, but the problem occurs when I want to load them through the plugin using "image conversation", an error message appears with metadata, for sentinel-2, when I did it in the same way there was no problem

**Comment by semiautomaticgit** [comment]
Hi @hukjhnilh , the image metadata is not compatible with the plugin. You can try to download the Landsat image using the plugin.
