### ISSUE TITLE
Adaptation to the Flatpak version of QGIS

### ISSUE THREAD

**Issue by Teclado** [semiautomaticgit/SemiAutomaticClassificationPlugin#353]
If you're using the Flatpak version of QGIS, the plugin installation complains about some python dependencies that are not satisfied. In particular scipy.

It would be possible you to include this dependencies to the plugin's code? Should I address the QGIS development team?

**Comment by semiautomaticgit** [comment]
Hello @Teclado ,
unfortunately it is not possible to include the dependencies in the plugin code.
You can try to ask the developers of the Flatpak version of QGIS.
