### ISSUE TITLE
No se pudo cargar el complemento 'scpplugin' debido a un error al llamar a su método classFactory()   ImportError: cannot import name 'home_plugin_path' from 'qgis.utils' (C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py) 

### ISSUE THREAD

**Issue by Judac0125** [semiautomaticgit/SemiAutomaticClassificationPlugin#356]
Hola presento este error  me pueden ayudar, necesito una solucion pronta 

No se pudo cargar el complemento 'scpplugin' debido a un error al llamar a su método classFactory() 

ImportError: cannot import name 'home_plugin_path' from 'qgis.utils' (C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scpplugin\__init__.py", line 27, in classFactory
    from .scpplugin import ScpPlugin
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scpplugin\scpplugin.py", line 27, in 
    from qgis.utils import home_plugin_path
ImportError: cannot import name 'home_plugin_path' from 'qgis.utils' (C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py)

Versión de Python: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Versión de QGIS: 3.36.2-Maidenhead Maidenhead, 6d250527 

Ruta de Python:
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass83\etc\python
C:\Users\julia\Documents
C:\Program Files\QGIS 3.36.2\bin\python312.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib
C:\Program Files\QGIS 3.36.2\bin
C:\Users\julia\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python312
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\julia\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AcATaMa\extlibs
C:\Users\julia\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\BitFlagRenderer
C:\Users\julia\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\BitFlagRenderer\bitflagrenderer
.
C:\Users\julia\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by semiautomaticgit** [comment]
Hello @Judac0125 ,

you actually installed a different plugin. You should install the Semi-Automatic Classification Plugin.
