### ISSUE TITLE
Multiple ROI Creator load points from text does not parse CSV file at comma.

### ISSUE THREAD

**Issue by evansf** [semiautomaticgit/SemiAutomaticClassificationPlugin#36]
I provide a CSV file of various formats.  All attempts result in the window reading the entire record (line) into the X field and then generate an error.

**Comment by semiautomaticgit** [comment]
Thank you. 
I've fixed this in version 6.1.4. 
The CSV should be separated by tabs or semicolon as in the attached example
[multiple_ROI.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/1910225/multiple_ROI.txt)

Best
