### ISSUE TITLE
PyTorch error

### ISSUE THREAD

**Issue by oguerrarea** [semiautomaticgit/SemiAutomaticClassificationPlugin#368]
After trying to make a preview classification the following message appears: SCP: multiprocess: error classification.
I make a debug and the following is the result:
![Screenshot 2024-08-04 232839](https://github.com/user-attachments/assets/7912a9f3-5320-47fd-9e6a-0972e4b22a57)
Attached is the debug log file:
[Debug_20240804.txt](https://github.com/user-attachments/files/16490790/Debug_20240804.txt)

Any solution?

thank you

**Comment by semiautomaticgit** [comment]
Hello @oguerrarea ,

you should install PyTorch, please follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html
