### ISSUE TITLE
Troubleshooting Band Processing Classification Issues in QGIS

### ISSUE THREAD

**Issue by HeinvdPaal** [semiautomaticgit/SemiAutomaticClassificationPlugin#375]
I am trying to perform a band processing classification, but it kept getting stuck at 1% and then QGIS would crash. I sort of fixed this by installing various things, like remotior_sensus, but now when I try to run it, I get an error message and I really don’t know what to do. I also asked AI for help, and it told me to install a bunch of things, but that didn’t help either.

![foutmelding](https://github.com/user-attachments/assets/d0cb01a4-1129-4c97-9c15-d65103eb2cef)

**Comment by semiautomaticgit** [comment]
Hello @HeinvdPaal , 
it seems an installation issue.
Please uninstall QGIS and the plugin and follow these installation steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html
