### ISSUE TITLE
Semi-Automatic Classification Plugin : 'NoneType' object has no attribute 'log' at QGIS startup in version 8.3.0

### ISSUE THREAD

**Issue by Antoviscomi** [semiautomaticgit/SemiAutomaticClassificationPlugin#377]
I just installed SCP on QGIS running on Ubuntu 22.04 with all python requirements an I receive : 
`2024-10-17T17:49:16     WARNING    Semi-Automatic Classification Plugin : 'NoneType' object has no attribute 'log'` 
in messages and 
` INFO    'NoneType' object has no attribute 'log'` 
in remotior sensus tab.
So I'm not able to open/use the SCP plugin as it is not initialized.
Any suggestion?

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head><body>

Versione di QGIS | 3.38.3-Grenoble | Revisione codice QGIS | 37f9e6efeec
-- | -- | -- | --
Versione Qt | 5.15.3
Versione Python | 3.10.12
Versione GDAL/OGR | 3.4.1
Versione PROJ | 8.2.1
Versione database del Registro EPSG | v10.041 (2021-12-03)
Compilato con GEOS | 3.10.2-CAPI-1.16.0 | Esecuzione con GEOS | 3.11.1-CAPI-1.17.1
Versione SQLite | 3.37.2
Versione PDAL | 2.3.0
Versione client PostgreSQL | 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.4
Versione QScintilla2 | 2.11.6
Versione SO | Ubuntu 22.04.5 LTS
  |   |   |  
Plugins Python attivi
SwapVectorDirection | 0.9
lizmap | 4.4.2
path_sorting | 0.3
DataPlotly | 4.1.0
SentinelHub | 2.0.2
SemiAutomaticClassificationPlugin | 8.3.0
e_tracability | 0.7
ORStools | 1.8.4
profiletool | 4.2.6
kmltools | 3.2.2
Cluster-Analysis-plugin-main | 1.0.1
clusterpoints | 6.1
qfieldsync | v4.10.1
processing_saga_nextgen | 1.0.0
dissect_dissolve_overlaps | 0.5
pg_raster_import | 3.2.0
polsar_tools | 0.7
corrector_vector | 0.3.1
BoundingBox | 2.2
db-style-manager | 0.8
pstimeseries | 1.1.1
StreetView | 3.2
oneclickrasterstacking | 1.1.0
dimensioning | 0.2
HouseNumbering3 | version 0.0.5
MultiJoin | 1.0
quick_map_services | 0.19.34
RenameField | 0.1
Qgis2threejs | 2.7.3
postgis_geoprocessing | 0.9
DAI | 0.2
profileexport | 0.5.1
CalculateGeometry | 0.6.9
citygen | 0.3
splitmultipart | 1.0.0
pgRoutingLayer | 3.0.2
QuickOSM | 2.2.3
veloroutes_voies_vertes | 1.0.0
tile_index_generator | 1.0
qgis_resource_sharing | 1.1.0-beta1
ClusterMap | 1.2
pluginbuilder3 | 3.2.1
realcentroid | 1.0.3
gribdownloader | 0.5
ArcheoCAD | 3.2.2
GeometryShapes | 0.7
PostGISQueries | 0.2
xplan-umring | 2.12.2
timemanager | 3.6
OSMDownloader | 1.0.3
openlayers_plugin | 2.0.0
NITK_RS-GIS_17 | 1.2
QuickWKT | 3.1
plugin_reloader | 0.17
postgis_toolbox | 1.2
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20

</body></html>Versione di QGIS
3.38.3-Grenoble
Revisione codice QGIS
[37f9e6efeec](https://github.com/qgis/QGIS/commit/37f9e6efeec)
Versione Qt
5.15.3
Versione Python
3.10.12
Versione GDAL/OGR
3.4.1
Versione PROJ
8.2.1
Versione database del Registro EPSG
v10.041 (2021-12-03)
Compilato con GEOS
3.10.2-CAPI-1.16.0
Esecuzione con GEOS
3.11.1-CAPI-1.17.1
Versione SQLite
3.37.2
Versione PDAL
2.3.0
Versione client PostgreSQL
14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
Versione SpatiaLite
5.0.1
Versione QWT
6.1.4
Versione QScintilla2
2.11.6
Versione SO
Ubuntu 22.04.5 LTS

Plugins Python attivi
SwapVectorDirection
0.9
lizmap
4.4.2
path_sorting
0.3
DataPlotly
4.1.0
SentinelHub
2.0.2
SemiAutomaticClassificationPlugin
8.3.0
e_tracability
0.7
ORStools
1.8.4
profiletool
4.2.6
kmltools
3.2.2
Cluster-Analysis-plugin-main
1.0.1
clusterpoints
6.1
qfieldsync
v4.10.1
processing_saga_nextgen
1.0.0
dissect_dissolve_overlaps
0.5
pg_raster_import
3.2.0
polsar_tools
0.7
corrector_vector
0.3.1
BoundingBox
2.2
db-style-manager
0.8
pstimeseries
1.1.1
StreetView
3.2
oneclickrasterstacking
1.1.0
dimensioning
0.2
HouseNumbering3
version 0.0.5
MultiJoin
1.0
quick_map_services
0.19.34
RenameField
0.1
Qgis2threejs
2.7.3
postgis_geoprocessing
0.9
DAI
0.2
profileexport
0.5.1
CalculateGeometry
0.6.9
citygen
0.3
splitmultipart
1.0.0
pgRoutingLayer
3.0.2
QuickOSM
2.2.3
veloroutes_voies_vertes
1.0.0
tile_index_generator
1.0
qgis_resource_sharing
1.1.0-beta1
ClusterMap
1.2
pluginbuilder3
3.2.1
realcentroid
1.0.3
gribdownloader
0.5
ArcheoCAD
3.2.2
GeometryShapes
0.7
PostGISQueries
0.2
xplan-umring
2.12.2
timemanager
3.6
OSMDownloader
1.0.3
openlayers_plugin
2.0.0
NITK_RS-GIS_17
1.2
QuickWKT
3.1
plugin_reloader
0.17
postgis_toolbox
1.2
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20

**Comment by semiautomaticgit** [comment]
Hello @Antoviscomi ,

thank you for reporting this.
It was already reported at https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/362, therefore please continue in that issue.
Unfortunately it seems an Ubuntu system issue.
