### ISSUE TITLE
Error [39] : Unable to find images

### ISSUE THREAD

**Issue by joaocarr** [semiautomaticgit/SemiAutomaticClassificationPlugin#378]
Hi,

I had to install a previous version 7.10.11, which seems to run alright. However, everytime I try to find Landsat data I get:

Error [39]: Unable to find images

Below a screenshot of the dialog box

Thank you!

![image](https://github.com/user-attachments/assets/50832425-bb46-4f3c-acc9-70406d113da6)

**Comment by semiautomaticgit** [comment]
Hi @joaocarr , 
unfortunately version 7 is not supported anymore.
This issue is related to the download services that were updated in the latest version 8 of SCP.
Please follow these installation steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html
