### ISSUE TITLE
Installation problem with Mac

### ISSUE THREAD

**Issue by rcabas** [semiautomaticgit/SemiAutomaticClassificationPlugin#38]
Hi,
I have some problems with the plug-in.
I attach the windows that appears when I try to start the plug-in.
Please, can you tell me what i need to do?
Thanks
![captura de pantalla 2018-05-28 a las 16 45 00](https://user-images.githubusercontent.com/39711017/40627771-557844a0-6297-11e8-977b-9798dc2ce52d.png)

**Comment by semiautomaticgit** [comment]
Hi, it is a dependency issue.
Please read this about installing dependencies https://gis.stackexchange.com/questions/274381/installing-qgis3-on-mac

Possibly this
sudo ln -s /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework /Library/Frameworks/Python.framework
then 
pip3 install matplotlib numpy scipy
