### ISSUE TITLE
Mini dump crash

### ISSUE THREAD

**Issue by fargotty** [semiautomaticgit/SemiAutomaticClassificationPlugin#41]
I have a Qgis 2.18 version and when I try to install the SCP plugin, the mini dump crash error goes out and immediately closes the qgis. Please, could you help me? Thank you so much
![mini dump error](https://user-images.githubusercontent.com/13203724/41686404-8d8356a4-74a9-11e8-973b-e29f3bd1692d.JPG)

**Comment by semiautomaticgit** [comment]
Hello, unfortunately it seems a QGIS issue,
Possibly the plugin installation is incomplete because of internet issues or system issues. You can try to disable any antivirus or firewall before installing the plugin, Also, you can try to install QGIS again,

**Comment by fargotty** [comment]
Dear Luca,
Thank you so much for your response.
I installed qgis 3 and SCP 6 and the problem was solved.
Right now, I am trying to preprocess the sentinel images but when I enter
the metadata the information of the bands does not appear and it does not
let me move forward. The image is:
S2A_OPER_MSI_L1C_TL_MTI__20160502T220520_A004498_T17MPN_N02.01.zip
Please, could you help me?


*Freddy Argotty M.Sc. Ing. Agroforestal *


2018-06-21 12:43 GMT-05:00 Luca Congedo <notifications@github.com>:

**Comment by semiautomaticgit** [comment]
Dear Freddy,
you should unzip the images and place all the .jp2 files in the same directory. Then use the preprocessing tool ignoring the metadata message.
Best,
Luca
