### ISSUE TITLE
Edit raster problems

### ISSUE THREAD

**Issue by gis2015** [semiautomaticgit/SemiAutomaticClassificationPlugin#45]
Hi.
**Problem 1**
The result does not appear on the screen and **it is no**t applied to the image (* .TIF file) when the new class (value) is applied using the SCP Menu Bar Controls.
**Problem 2**
The result does not appear on the screen **but it is** applied to the image (* .TIF file) when the new class (value) is applied using the Edit Values dialog box (Edit Values Using ROI Polygons combined with Use Constant Values or with Use Expression; Values Using the Vector combined with Use Constant Values or with Use Expression). To see the result it has been necessary to remove the layer and add it again.
QGIS: 3.2.3; SCP: latest update; Windows 10.

**Comment by semiautomaticgit** [comment]
Hi, thank you for reporting this.
About the first problem, can you try editing a classification raster produced with SCP?
About the second problem, it is a known issue of refresh. Usually the new values are shown after zooming out and zooming in. I'll try to find a workaround for that.

**Comment by sopheatip99** [comment]
Dear Bro Luca,
I use Editing raster as below:
1: load classification image to QGIS
2:load classification image to Bandset
3:laod classification image to Editing raster (Edit value using ROI)
4: Draw ROI
5. Assign value in Editing Raster

However, It sometime works and sometime not. what the problem

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
