### ISSUE TITLE
NameError: name 'd' is not defined

### ISSUE THREAD

**Issue by kadirsahbaz** [semiautomaticgit/SemiAutomaticClassificationPlugin#46]
In `maininterface/erosionTab.py`, line 81 (`sN=cfg.osSCP.path.basename(str(d))`) throw this error: `NameError: name 'd' is not defined`. 

`d` doesn't exist and `sN` is not used in the file. I guess it should be deleted or changed to line comment.

**Comment by semiautomaticgit** [comment]
Thank you, I'll fix this
