### ISSUE TITLE
Vector to Raster Problem

### ISSUE THREAD

**Issue by Scibeeria** [semiautomaticgit/SemiAutomaticClassificationPlugin#48]
I am trying to convert the vector for a cloud mask to a raster following your excellent video tutorial. I follow all your steps for "Vector to Raster." For some reason, the screen that I receive when I hit run is not the same as the video. There is no save "raster output screen," but a similar screen to saving the vector file. I type in mask.tif (screenshot) and the execution dialogue runs straight to 100% and stays there. When I hit cancel, I get a red line with Error [34] Clip area outside image.

I look forward to you "switching on the light" for me.

Cheers,
Peter

**Comment by semiautomaticgit** [comment]
Hello Peter,
please follow these steps to copy the SCP log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by Scibeeria** [comment]
Luca,

Thank you so much for your quick response. I am a neophyte with satellite image processing, but I am warming to your plugin. Your tutorials are great.

I have run the process with a Sentinel image and not the sample dataset. I will try that next. For now, here is the log file from the debug process.

Cheers,
Pete

**Comment by semiautomaticgit** [comment]
Thank you Peter, I'm glad that you appreciate my work.
About the issue, I think it is related to the GML mask. You can try to save the gml file as shapefile and define the coordinate reference system as WGS 84.

**Comment by Scibeeria** [comment]
Luca,

My apologies. This is a new language for me. What do you mean by GML?

Cheers,
Peter

**Comment by Scibeeria** [comment]
Luca,

I realised that the GML file is the cloud mask that comes with the Sentinel data. Yes, I saved that as an ESRI shape file before doing the Vector to Raster conversion. I just can’t the conversion to prompt me to save a TIF file.

Cheers,
Pete

From: Peter Flindell <peter@flindell.org>
Date: Sunday, 11 November 2018 at 11:13
To: semiautomaticgit/SemiAutomaticClassificationPlugin <reply@reply.github.com>, semiautomaticgit/SemiAutomaticClassificationPlugin <SemiAutomaticClassificationPlugin@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [semiautomaticgit/SemiAutomaticClassificationPlugin] Vector to Raster Problem (#48)

Luca,

My apologies. This is a new language for me. What do you mean by GML?

Cheers,
Peter

**Comment by semiautomaticgit** [comment]
You can try to check the checkbox "Use constant value"

**Comment by Scibeeria** [comment]
Luca,

This box is checked. I still get the wrong dialogue box to save the raster.

Cheers,
Pete

**Comment by semiautomaticgit** [comment]
Thank you, I'll look into it

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
