### ISSUE TITLE
Styling doesn't play so well with dark themes

### ISSUE THREAD

**Issue by nirvn** [semiautomaticgit/SemiAutomaticClassificationPlugin#49]
While helping our a user out there, I noticed the custom styling this plugin applies to its toolbars (and probably other parts), does not play so well with dark themes, so for e.g. the labels in this toolbar:
![image](https://user-images.githubusercontent.com/1728657/51602484-abf3f680-1f39-11e9-8a2d-45ef8edaf221.png)

I'd advice against custom styling as much as possible, esp when it comes to toolbars.

**Comment by semiautomaticgit** [comment]
Thank you. I'll try to fix this.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
