### ISSUE TITLE
When searching for Sentinel granulas I get "Error [50]: Internet error"

### ISSUE THREAD

**Issue by mabdelrazek** [semiautomaticgit/SemiAutomaticClassificationPlugin#5]
Hello,
thanks for the nice plugin, comprehensive and easy to use. 

Landsat download and processing work nicely, but Sentinel download didn't work. I tried to search for and download Sentinel 2 images on Mac 10.11, Ubuntu 14.04 and Windows 10 and got the same results "Error [50]: Internet error". I have also created and used 4 different  scientific hub accounts, still no success.

Antivirus=off, Firewall=off

I have on Windows for instance QGIS 2.16, full installation using osgeo4w-setup (including SAGA GIS)

Is there is something I missing here?

Thanks,
mohammad

**Comment by semiautomaticgit** [comment]
Hello Mohammad, and thank you for using SCP.
You should enter user: guest and password: guest .
Also, there is a known issue with this workaround http://fromgistors.blogspot.com/2016/06/sentinel-2-download-issues.html

**Comment by mabdelrazek** [comment]
Thanks Luca,

I upgraded python on Ubuntu and also downloaded the virtual machine and both works!

Best,
mohammad

**Comment by semiautomaticgit** [comment]
You are very welcome.
I am glad it worked.

Best,
Luca
