### ISSUE TITLE
Error: The memory dump is saved in the file C: \ Users \ 77021 \ AppData \ Local \ Temp \ qgis-20190124-162755-11392-17660-6551c2a73e.dmp

### ISSUE THREAD

**Issue by Kitapbayev** [semiautomaticgit/SemiAutomaticClassificationPlugin#50]
Hi! After installation of plugin QGIS crashes with error:  The memory dump is saved in the file C: \ Users \ 77021 \ AppData \ Local \ Temp \ qgis-20190124-162755-11392-17660-6551c2a73e.dmp

I have tried to re-install QGIS few times, but error repeatd again. 

I work on Windows 10. 
QGIS version: 2.18.28. 
SCP version: 5.4.2

Looking forward for your reply!
Best regards,
Almas

**Comment by semiautomaticgit** [comment]
Please try to remove the plugin directory in the .qgis2 folder in the user directory

**Comment by Kitapbayev** [comment]
I have tried, but it didn't help. I have tried to install it automaticaly and manually. Another thing is that we have another computers were older versions of QGIS (2.18.20) and SCP (5.3.8) are installed, after update of SCP error repeats in the same way.

**Comment by semiautomaticgit** [comment]
I think it is an issue with the QGIS installer. Please open a ticket here https://issues.qgis.org/issues/ including the memory dump

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
