### ISSUE TITLE
RecursionError during start

### ISSUE THREAD

**Issue by Marwe** [semiautomaticgit/SemiAutomaticClassificationPlugin#54]
Currently the plugin does not load here in my QGIS, due to a RecursionError.
Does anybody have an idea what could be wrong? Is it a config issue or dependencies? Maybe I am missing something.

Error log example is attached
[scp_recursion_load_error.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/2927940/scp_recursion_load_error.txt)

**Comment by semiautomaticgit** [comment]
Hello, please try to uninstall QGIS and install it again

**Comment by Marwe** [comment]
Thanks, but I am on Linux here and install qgis from packages, so there is not too much to be different after a reinstall (That may vary on Windows/other hosts). Did it anyway and found no change, still the same error.

Oops, a reinstall of the SCP plugin now crashes qgis, log/stacktrace on commandline looks identical.
`SIGABRT in Py_FatalError()` seems not to be catched/try-excepted by Extension module.
After the crashed install the SCP plugin is installed (and throws the known error, caught in a window at startup).

Any other idea how to debug this?

So much thanks for this great piece of software!

**Comment by semiautomaticgit** [comment]
You are very welcome.
Unfortunately I think it is an issue related to QGIS package. Can you try to install a different QGIS version?

**Comment by Marwe** [comment]
What version would be required, < 3.x (2.18) or > 3.4?
Unfortunately, on Linux one cannot install different Versions in parallel easily, since there are certain dependencies for each version installed, and you cannot have those parallel in different versions. 
I am looking into running it virtualised (tried a docker instance, but might need a full install for extensions). TBD...

**Comment by Marwe** [comment]
Just tried a fresh install of QGIS 3.4.5 on Ubuntu 18 (bionic, with ubuntugis-unstable), 2.18 is history anyway: [End of life notice: QGIS 2.18 LTR](http://blog.qgis.org/2019/03/09/end-of-life-notice-qgis-2-18-ltr/). 

All fine there, so I might need to look into some of my (python) dependencies on my ubuntu 16...

**Comment by semiautomaticgit** [comment]
Thank you for your feedback. Yes, QGIS issues are generally related to dependencies for Linux.

**Comment by Marwe** [comment]
Just for information, there are no issues on a fresh install on QGIS 3.4 in Ubuntu xenial (16.04) as well. I tested this via virtualbox.
So this issue can be closed, I need to look into my system.

Thanks for your time and the great work!

**Comment by semiautomaticgit** [comment]
You are very welcome.
Thank you for your feedback.
