### ISSUE TITLE
Radiometric Calibration in Atmospheric Correction？

### ISSUE THREAD

**Issue by licaoyu** [semiautomaticgit/SemiAutomaticClassificationPlugin#57]
It's very uesful with this tool when processing remotesensing imgery,but I have a question that after applying DOS1 Atmospheric Correction with Landsat8（OLI）product，the output file with bands have ever done the Radiometric Calibration .As far as I know , Radiometric Correction includes Radiometric Calibration and Atmospheric Correction，but I don't find any module can do the first job. Also ,I found there is a explainlation about Radiometric Calibration  at your document on your offcial site.
      If trere is not Radiometric Calibration in this plugin , how can I do the Radiometric Calibration with a output file that can be processed with your DOS1 Atmospheric Correction？

**Comment by semiautomaticgit** [comment]
Hello, you can find the code about conversion to reflectance with and without DOS1 correction here https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/blob/master/maininterface/landsatTab.py#L407

If you have other questions please ask in this group https://www.facebook.com/groups/SemiAutomaticClassificationPlugin/
