### ISSUE TITLE
Prepocessing Atmospheric Correction

### ISSUE THREAD

**Issue by gis2015** [semiautomaticgit/SemiAutomaticClassificationPlugin#58]
Hi, Luca.

**The source of the problem was an error in band 3. Please disregard this issue.**

_The atmospheric correction preprocessing is stopped working and does not reach the end of the process.
Follows attached bug report.
QGIS 3.4.8.
[Log_Preprocessing_Atm_corr.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/3232788/Log_Preprocessing_Atm_corr.txt)_

**Comment by semiautomaticgit** [comment]
Thank you for your report
