### ISSUE TITLE
While running classification : Error exception: 'str' object has no attribute 'dataProvider'

### ISSUE THREAD

**Issue by AntoineMath** [semiautomaticgit/SemiAutomaticClassificationPlugin#59]
I created several polygones in order to use the classification algorithm.
I can run the classification but close to the end of the processing, an error occured and the plugin freeze.

[log_error.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/3309199/log_error.txt)

QGIS version : 3.4.6-Madeira
Python : 3.7.2

i have these errors on my terminal too  (dont know if it related to my first problem):

```
ERROR 1: TIFFAppendToStrip:Seek error at scanline 2249
ERROR 1: _tiffSeekProc:Aucun espace disponible sur le périphérique
```

(I have these errors more than 1000 times, so I think my raster is too large (10980 x 10980 x 4bands)

EDIT : I found an ugly but working way : I save the preview as a .tif.
And I found that when I tried to do a too large preview I get a similar error : 
`"str" object has no attribute "name"`

So maybe my initial error is due to a too large file, but I rly don't understand why

**Comment by semiautomaticgit** [comment]
Hello, please check that there is enough free space on hard disk. You can also change the temporary directory in settings https://semiautomaticclassificationmanual.readthedocs.io/en/latest/main_interface_window.html#processing

**Comment by devesh962** [comment]
I'm facing the same error in MacOS everything is working fine but when i run the classification this error pops up
![Screenshot 2020-07-20 at 02 22 01](https://user-images.githubusercontent.com/41562861/87907870-087a9800-ca83-11ea-857b-c16e869573f8.png)

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it

**Comment by andierupp** [comment]
I'm having this same issue and I can't run version 7 since I'm on a mac. I've got plenty of space on my hard drive as well. Running SCP 6.4.7, QGIS 3.10, and python 3.7.

**Comment by semiautomaticgit** [comment]
> I'm having this same issue and I can't run version 7 since I'm on a mac. I've got plenty of space on my hard drive as well. Running SCP 6.4.7, QGIS 3.10, and python 3.7.

@andierupp unfortunately version 6 is now unsupported. 
Other users successfully installed the version 7 on MacOS 
Please update to version 7 following this guide, https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation_mac.html
