### ISSUE TITLE
merging of ROIs

### ISSUE THREAD

**Issue by DmitryChern** [semiautomaticgit/SemiAutomaticClassificationPlugin#60]
Hello, dear Luca!
Could you explain one theoretical item of classification?
I do not understand the difference between using a set of separate ROI signatures (each line for each C ID) and merged ROI (one line for the group of C ID, more obvious – one line for one merged MC ID). For me, using the merged MC ID is more convenient both for assessment of separate plots and for further processing. But I found the difference between the results of processing separately the ROI signatures (classification by MC ID) and the results of  processing the combined MC ID. An example is after merging some ROIs, the resulting line may have a different number of pixels (less than the sum of the separately ROI signatures). The results of classifications for merged and separate ROIs are also different (accuracy characteristics)
My question. Could you recommend using a combined ROI for classification (or the results of the classification may be incorrect and it would be better to use a set of separate ROIs)?
Thank you.
Dmitry

**Comment by semiautomaticgit** [comment]
Hello Dmitry, 
the use of separate ROI signatures or merged ones depends on selected classification algorithm.
For instance, Maximum Likelihood requires large ROIs to calculate the covariance matrix. 
Generally, you should merge ROIs only if you need to mix the spectral characteristics in order to increase the variability of signature values. In other cases I'd suggest to use separate ROIs.

**Comment by DmitryChern** [comment]
Hello, Luca!
Thank you very much for answer.
We conduct research in field of forestry (find and assessment of uncovered forest areas). And we try to use all possible algorithms (to compare results of classification and choose the best algorithm). At just moment we have got the best results for Minimum distance.
Could you say whether the difference between the classification results for individual ROI signatures or combined signatures will be very significant? (e.g. 1-5 percent accuracy or more)?
Next question. Why sums of pixels aren’t equal:
- in the Signature details table (the sum of pixels of the separate ROI signatures is greater than the number of pixels for the merged ROI),
- between the classes of error matrix (in the lowest row of the “Total” error matrix) and the «number of pixels» row in the Signature details table?

If it (a different number of pixels for the same classes in different SCP windows) is normal, then where is the true number of pixels in the  classes (in «Total» line of error matrix, or in the lines of Signature details table)?
Thank you.
Dmitry

**Comment by semiautomaticgit** [comment]
Hello,
about the difference in results it is not possible to foresee the results, because there are many variables including spectral similarity of land cover classes.
About the different sum of pixels, is it possible that some of the ROIs are overlapping?

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
