### ISSUE TITLE
Error [21]: Internet connection failed

### ISSUE THREAD

**Issue by nikosGeography** [semiautomaticgit/SemiAutomaticClassificationPlugin#62]
Hello, I am trying to insert a map using the 
_Add OpenStreet Map to the map._
and I get the following error 
_Error [21]: Internet connection failed_
even though I have internet connection. Also, when I try to download images I'm getting a sound and nothing happens (I insert the correct Username and Password at Login data dialog box).
I want to download Landsat 5 Band 6.
I am using Windows, QGIS 3.6 and the Python 2.7.8. Lastly, the Available RAM is set to the half (1.9GB out of the available 4).

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
