### ISSUE TITLE
Pixel size changes when processing Sentinel 2 band 12 data

### ISSUE THREAD

**Issue by BiggusDaveus** [semiautomaticgit/SemiAutomaticClassificationPlugin#65]
Hi there,

I am trying to use SCP to download Sentinel 2 data and convert to indices. I want to create both NDVI using Band 4 and 8 and STR (using band 12). The resolutions of these bands are 10m for 4 and 8 and 20m for Band 12. 

I do the processing using DOS1 as per instructions, however I then want to align the rasters to resample band 12 to 10m to match with bands 4 and 8. I noted that the pixel and image size for Band 12 was now the same as Band 4 and 8, however the pixels are still the full 20m (when measured).

Perhaps I am doing something wrong in the conversion/preprocessing but I don't see where I am making a mistake. 

Any help with this matter would be greatly appreciated!

Thanks,

Dave O'Leary

**Comment by semiautomaticgit** [comment]
Hello Dave O'Leary,
bands with 20m spatial resolution are resampled to 10m resolution without changing the original pixel value (i.e. one 20m pixel is divided in four 10m pixels with the same value).
This allows calculations without changing original values.
Best

**Comment by BiggusDaveus** [comment]
Thanks alot,

Thats all cleared up now!!

Cheers for the quick response.

Dave
