### ISSUE TITLE
Maximum Likelihood algorithm unstable

### ISSUE THREAD

**Issue by gis2015** [semiautomaticgit/SemiAutomaticClassificationPlugin#66]
Hi Luca.
Both preview and classification using the Maximum Likelihood algorithm appear to be unstable.
a) The results are shown correctly for several times, but suddenly the algorithm stops working well.
b) The results are shown correctly for several times, but the algorithm fails to work well when the training file is reloaded.
The unexpected result considers only the first macro class or the first class.

Jeffries-Matusita distance > 1.67

Windows 10
QGIS 3.4.11

[log_01.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/3566462/log_01.txt)

**Comment by semiautomaticgit** [comment]
Hello and thank you. 
I'll try to look into this.

**Comment by semiautomaticgit** [comment]
Hello, unfortunately I couldn't reproduce this issue.
Could you please use [this dataset](https://drive.google.com/open?id=10SRrNbiy-f2uaX3e7jHdw4dI8sG9bIE4) and report the log file.

**Comment by gis2015** [comment]
Hi Luca
Thank you for your attention.
I've been reviewing all the steps.
The instability has been due to user errors (fortunately).
For example, repeating the number of a class already assigned to another class.
These errors could be alerted and prevented by SCP.
I am preparing some suggestions that I think may help in preventing user errors.
One of the suggestions follows below.
Please see in the accompanying text that the results with correctly numbered classes (without repeating numbers) are the same as the results with incorrectly numbered classes (restarting at 1 for each macroclass). These results encourage the user to understand that one can organize classes as: 
1 - Macroclass A (1 - class A1, 2 class A2 ...); 
2 - Macroclass B (1 class B1, 2 class B2 ...) and so on. 
Mistakenly, the user can understand that class 2 that belongs to macroclass B is indexed in SCP as 2.2 - class B2.
Would it be possible to insert a verifier that would alert the user when creating a new class with a number already used in another class (idem for macroclasses)?
[SCP_01.pdf](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/3662956/SCP_01.pdf)

**Comment by semiautomaticgit** [comment]
Thank you very much for your feedback.
I appreciate your suggestions. I think I can implement a notification about classes and macroclasses combinations in a future update of the plugin.
