### ISSUE TITLE
training.scp file for tutorial

### ISSUE THREAD

**Issue by ams-purdue** [semiautomaticgit/SemiAutomaticClassificationPlugin#67]
Hi,
I'm using your plugin for QGIS and following along in your tutorial https://semiautomaticclassificationmanual-v5.readthedocs.io/en/latest/tutorial_1.html. Thank you greatly for having that. However, I was wondering if you had a training.scp file ready made that could be loaded, just so I could see a  "completed" one, and run the classification with it (and compare the results to mine). 
If you don't have one, no worries. 
Thank you in advance for your time,
Amelie

**Comment by semiautomaticgit** [comment]
Hello Amelie,
unfortunately I don't have the scp file, but I'm sure you can collect better ones.
Also, please follow this updated tutorial https://semiautomaticclassificationmanual.readthedocs.io/en/latest/tutorial_1.html
