### ISSUE TITLE
Feature Request: (Classification Preview) Algorithm Raster++

### ISSUE THREAD

**Issue by javaftw** [semiautomaticgit/SemiAutomaticClassificationPlugin#69]
A **dual-level histogram stretch slider** for the preview raster. The sliders set lower/upper cut-off bounds to the slice of the histogram to stretch in the preview. Makes it much easier to see slight differences in specific areas.

The Algorithm Raster shows how close a pixel is to its nearest classified signature and answers the question "to what extent are the pixels classified?". Another such type of raster can depict **how close close a pixel is to neighbouring classifications** by means of a gradient (heatmap) colour palette - the closer (hotter) the nearby signatures are, the higher the likelihood of misclassification/class-confusion - and the pixel brightness depicts the average distance to all signatures (similar to the current raster).

**Comment by semiautomaticgit** [comment]
Hello @javaftw , I'm also closing this because of the new version 8 of SCP.
Thank you very much for the suggestion, but unfortunately  I'm not able to implement it.
