### ISSUE TITLE
UnboundLocalError: local variable 'reml' referenced before assignment in SCP 6

### ISSUE THREAD

**Issue by KarinVier** [semiautomaticgit/SemiAutomaticClassificationPlugin#70]
Hi,
I am getting this error while trying the accuracy assesment in SCP version 6.
UnboundLocalError: local variable 'reml' referenced before assignment in SCP 6 (see attached)

I saw a previous (now closed) issue that mention this issue should be fixed in version 6. Am I doing anything wrong?
![SCP6_Accuracy_error](https://user-images.githubusercontent.com/55690357/65415414-02317600-ddf6-11e9-8404-17dad644ef5c.png)

**Comment by semiautomaticgit** [comment]
Hi, possibly this is related to input data issues.
Please copy the log file
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by KarinVier** [comment]
Many thanks for your fast reply. I was helping someone out, who has rechecked the input data and seems to have solved the problem. (Sorry I didn't get any details to let you know what exactly was wrong, so not very helpful to the community).
Thanks for this great plugin!
