### ISSUE TITLE
In Batch mode, clip_multiple_raster, Which is the correct route for vector_path?

### ISSUE THREAD

**Issue by WenaSeba** [semiautomaticgit/SemiAutomaticClassificationPlugin#71]

**Comment by semiautomaticgit** [comment]
Hello, you should use 
clip_multiple_rasters;input_raster_path : '';output_dir : '';use_shapefile : 1;shapefile_path : '';nodata_value : 0;output_name_prefix : 'clip'

**Comment by WenaSeba** [comment]
Yes, I know but it doesn’t recognize any vector path that ends in .shp

**Comment by semiautomaticgit** [comment]
Please copy the log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
