### ISSUE TITLE
Error 40/Unable to connect

### ISSUE THREAD

**Issue by chhigansharma** [semiautomaticgit/SemiAutomaticClassificationPlugin#72]
I'm trying to download landsat 7 data from SCP plugin for the year 2010-11 , SCP showing error 40 that is unable to connect..i'm using qgis 3.6.11 with full internet connectivity

**Comment by semiautomaticgit** [comment]
Thank you, I'll look into this.

**Comment by chhigansharma** [comment]
Thank you, let me know if u need more information

**Comment by semiautomaticgit** [comment]
Hello, I run a few tests and I can download Landsat 7 images.
Possibly it is a network error.
Please follow these steps to copy the log file
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by mkmushegh** [comment]
Same error for me as well

**Comment by semiautomaticgit** [comment]
> Same error for me as well
> For the possible fix please follow the steps indicated in the Craig Glennie post with the following link:
> https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

Hello, what operating system are you using?

**Comment by mkmushegh** [comment]
> > Same error for me as well
> > For the possible fix please follow the steps indicated in the Craig Glennie post with the following link:
> > https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
> 
> Hello, what operating system are you using?

macOS Mojave (version 10.14.6)

**Comment by semiautomaticgit** [comment]
You can try to install QGIS from this site https://www.kyngchaos.com/software/frameworks/

**Comment by semiautomaticgit** [comment]
Possibly related to this
https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/111

**Comment by mbowdenp** [comment]
Hi there,

I have the same problem. I'm using qgis 3.26.3-Buenos Aires with a stable internet connection. I am running on MacOS Monterey (version 12.1). 

Any help is greatly appreciated, thank you.
