### ISSUE TITLE
Band Set reference to layer name

### ISSUE THREAD

**Issue by fpirotti** [semiautomaticgit/SemiAutomaticClassificationPlugin#73]
Hello Luca, thanks for your huge efforts in creating this plugin: a note on BandSets from pre-processing: if I open an image  (e.g. L1-C Sentinel-2)  and run preprocessing twice  with and without DOS1, selecting of course different folders, and checking the "create bandset and use bandset tools"+"Add bands to new bandset" options,  the two new BandSets will both refer to the latest created set of bands, due to elements in the bandset referring to layer names which are identical, and not the the folder path. **Am I correct assuming this, and that having layers with identical names will create confusion in using bandsets ?**
Below an image with an example: 
- **0** (Vrt Bandset3) is from preprocessing with DOS1 results, 
- **1** is B02 resulting from preprocessing without DOS1, 
- **2** (Vrt Bandset2) is from preprocessing without DOS1, 
- **3** is B02 from preprocessing witht DOS1. 
So values in 1 and 2 should be the same but instead 1 is different and 0, 2 and 3 are all the same because the bandset picks up the layer names and overlaps identical names. 
![immagine](https://user-images.githubusercontent.com/1391292/68069469-acd77580-fd60-11e9-95fc-6213b6a4c0ce.png)

**Comment by semiautomaticgit** [comment]
You are very welcome.
Yes, the Band set uses layers name, therefore identical names should be avoided.
