### ISSUE TITLE
Python error when starting the classification preview

### ISSUE THREAD

**Issue by Meteo-weather** [semiautomaticgit/SemiAutomaticClassificationPlugin#75]
When I am starting the classification preview I get an message that a Python error has occurred. 
[Log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/3896223/Log.txt)

**Comment by Meteo-weather** [comment]
AttributeError: 'str' object has no attribute 'name' 
Traceback (most recent call last):
  File "/Users/nicobader/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 350, in pointerClickPreview
    self.createPreview(cfg.pntPrvw, self.algRasterPrevw )
  File "/Users/nicobader/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 168, in createPreview
    cfg.lastPrev = r.name()
AttributeError: 'str' object has no attribute 'name'

This Is the information i get in the stacktrace!

**Comment by semiautomaticgit** [comment]
Hello, it is an issue related to QGIS installation of GDAL dependency. Please try to reinstall QGIS from https://www.kyngchaos.com/software/qgis/

**Comment by giusme** [comment]
Hi, I reinstalled QGIS 3.12 from https://www.kyngchaos.com/software/qgis/ but the classification preview is not working and I get a new Python error message: AttributeError: module 'time' has no attribute 'clock'.

**Comment by semiautomaticgit** [comment]
> Hi, I reinstalled QGIS 3.12 from https://www.kyngchaos.com/software/qgis/ but the classification preview is not working and I get a new Python error message: AttributeError: module 'time' has no attribute 'clock'.

please update the plugin to the latest version

**Comment by giusme** [comment]
Already done..But I still have the same Python error message...

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
