### ISSUE TITLE
Accuracy assessment - confusion matrix - error in overall accuracy

### ISSUE THREAD

**Issue by pkolokoussis** [semiautomaticgit/SemiAutomaticClassificationPlugin#78]
Hi Luca,

One of my students noticed that, in the accuracy assessment statistics, when she devides the diagonal elements of the confusion matrix by the total number of samples the result does not equal the overall accuracy which is calculated by the program. I tried it in different machines running windows and linux and it seems to be so, while it used to be calculated correctly in past versions.
Could you please check it out? Could it be an issue of regional settings?

![minimum](https://user-images.githubusercontent.com/22965873/71277957-ee4ad100-235e-11ea-875b-d5886b9a59c4.png)

**Comment by semiautomaticgit** [comment]
Hello, with SCP v 6.4 there is a new method for calculating accuracy statistics according to the area based error matrix.
Please read https://semiautomaticclassificationmanual.readthedocs.io/en/latest/tutorial_3.html and for reference Olofsson, P.; Foody, G. M.; Herold, M.; Stehman, S. V.; Woodcock, C. E. & Wulder, M. A., 2014. Good practices for estimating area and assessing accuracy of land change. Remote Sensing of Environment, 148, 42 – 57

**Comment by pkolokoussis** [comment]
Ah, OK! I had not checked the tutorial. Thank you Luca :)
