### ISSUE TITLE
SCP5.0 crashed when temporal preview files remove

### ISSUE THREAD

**Issue by ynobu14001** [semiautomaticgit/SemiAutomaticClassificationPlugin#8]
After created ROI and made previews of classification.
Then I pushed the dust button to clean up temporal files of preview then 
always crashed with such below error.

>minidum written to C:  
/users/  /AppData/Local/Temp/qgis-20160903-115800-9460-7568-8545b3b.dmp

PC: 
Windows10 pro and 7 pro Japanese ver.
QGIS 2.16.1 or 2.16.2

This problem was happened in previous SCP when preview data removed but it happened sometimes.

**Comment by semiautomaticgit** [comment]
Thank you for reporting this

**Comment by semiautomaticgit** [comment]
Thank you.
Fixed this in v. 5.0.2

Cheers
