### ISSUE TITLE
installing SCP causing crashes in QGIS 3.4

### ISSUE THREAD

**Issue by surfeyor** [semiautomaticgit/SemiAutomaticClassificationPlugin#80]
I'm having lots of issues getting SCP to intstall.  (*Running QGIS 3.4.14 on Mac OSX 10.13.6*)

Using the QGIS plugin manager to install will cause QGIS to crash, the progress bar will do its thing for several seconds after pressing "install plugin"  then it stops and QGIS crashes.

When reopened the plugin is installed but disabled, checking the box to enable it instantly causes a crash.

I have tried:

*Uninstalling QGIS 3.4.11 and installing QGIS 3.4.14

*connecting to the SCP repository and installing the master plugin (same result)

*downloading the master plugin from  _**https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/archive/master.zip**_  and manually installing by pasting the folder "SemiAutomaticClassificationPlugin" into the QGIS plugins directory 

I have also tried installing matplotlib and SciPy using terminal commands but that's getting of out of my depth, so not sure if that was successful.

Any help would be very much appreciated.

**Comment by semiautomaticgit** [comment]
Hello, you can try to install QGIS from this site https://www.kyngchaos.com/software/frameworks/

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
