### ISSUE TITLE
Unable to resize QGIS window after installing SCP

### ISSUE THREAD

**Issue by RobiFag** [semiautomaticgit/SemiAutomaticClassificationPlugin#81]
Hi,
I get some problems in resizing the QGIS (v. 3.4.15) window after installing the SCP Plugin on Windows 10. For instance I don't see the status bar anymore and I can't resize the height of the window. If I disable the plugin, the window works fine.
Attached a .gif file in which the problem is shown.

![unable_resize_window](https://user-images.githubusercontent.com/25825472/73753759-77796400-4763-11ea-804f-0e09c8584507.gif)

**Comment by semiautomaticgit** [comment]
Hello, you should move the SCP dock on top of other docks (or viceversa) to resize the window properly
