### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by skualos** [semiautomaticgit/SemiAutomaticClassificationPlugin#82]
In a few places in [/core/utils.py](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/blob/master/core/utils.py) the .clock() function is called.

In Python 3.8 this raises the above error. From the [Python docs](https://docs.python.org/3/whatsnew/3.8.html):

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

I replaced .clock() with .process_time() and got it working, But not sure which of the two options would be better suited.

**Comment by semiautomaticgit** [comment]
Thank you very much for reporting this. I'll fix this in a future update
