### ISSUE TITLE
Create Band Set

### ISSUE THREAD

**Issue by josepsitjar** [semiautomaticgit/SemiAutomaticClassificationPlugin#84]
Working with QGIS 3.10 and SCP 6.4.2 under Ubuntu 18.04, I can't save a Band Set. I click on Run and specify a directory, but anything happens.
No error is displayed, simply the band set is not created. 

Under windows, I've no problems. 

Thanks

**Comment by semiautomaticgit** [comment]
Hello, please follow these steps to copy the log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by josepsitjar** [comment]
Ok Luca, 
I attach the log file.

Thanks!

[logfile.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4274565/logfile.txt)

**Comment by Ahmed-Abdullah88** [comment]
I have the same problem stacking Sentinel-2 bands, (under Ubuntu 18.04.4, QGIS version 3.12.1 and SCP version 6.4.2), the error in the debug tab: 
SemiAutomaticClassificationPlugin.maininterface.bandsetTab-bandSetTools 1223	 ERROR exception: list index out of range
[error_log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4413908/error_log.txt)

Thanks.

**Comment by semiautomaticgit** [comment]
> Ok Luca,
> I attach the log file.
> 
> Thanks!
> 
> [logfile.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4274565/logfile.txt)

I think you didn't check the option to stack the bands or create a virtual raster before clicking RUN

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
