### ISSUE TITLE
New Macro Class ID is not created automatically in the macroclass panel when editing an existing MC

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#87]
Macro class are not created automatically in the macroclass panel when we do the following: 1) creating a ROI with the same MC ID than a previously existing MC ID and saving that ROI; 2) then changing the MC ID of the lastly created ROI to a new not yet existing MC ID, by editing the signature list panel. under Qgis 3.10, SCP 6.4.2. Windows.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
