### ISSUE TITLE
SCP Documentation error 5.1.1.1. Sample Design

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#88]
In the SCP manual section 5.1.1.1. Sample Design,
the formula
N=...(Wi−Si)...

should be corrected I think.

the - should be a *

N=...(Wi*Si)...
according to the computation made in the given example
(N=(0.2382/0.01)2=567 )

**Comment by semiautomaticgit** [comment]
Thank you. 
I'm closing this because of the new version 7.
