### ISSUE TITLE
Where can I find the code for the Earlier versions of the Plugin

### ISSUE THREAD

**Issue by devdattaT** [semiautomaticgit/SemiAutomaticClassificationPlugin#9]
I'm looking at the code, and In the earlier versions, I can see 4.9.0 as the previous version.

But on the Qgis site, You can find other older versions as well, such as: 4.9.6

https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/version/4.9.6/

Where can I find the code for these intermediate versions?

**Comment by semiautomaticgit** [comment]
Hello, the code of those versions are only on https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/
