### ISSUE TITLE
correction to text of pop up window of calculator expression

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#94]
1)in the band calc > expression > calculator > where function: the french pop up text window referes to nodata function. it should be corrected.  confer image.
2) here https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/blob/master/i18n/semiautomaticclassificationplugin_fr.ts?fbclid=IwAR17zBiHXttBUqRAuakZasnvxhH3h-fQpUaQD0QVJtnryXp2f0AbHMvOb9Y
the english pop up text seems missing. confer 2nd image

![image](https://user-images.githubusercontent.com/44610746/78000904-436e8980-7335-11ea-9bf1-856d662adcf8.png)
![image](https://user-images.githubusercontent.com/44610746/78001060-757feb80-7335-11ea-8af1-ed05747cdf38.png)

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
