### ISSUE TITLE
Corrections to french ui of SCP

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#99]
I think many POP UP TEXT windows should be corrected for the same mistake: confer the images
"Numéro de bande" should be replaced by "Numéro du jeu de bandes" as it refers to band set and not to a particular band. I was not able to find where to correct that in a pull request.

![Numero de bande should be Numéro du jeu de bandes 2](https://user-images.githubusercontent.com/44610746/78079594-b9620780-73ac-11ea-8b67-b4d944808ab7.PNG)
![Numero de bande should be Numéro du jeu de bandes](https://user-images.githubusercontent.com/44610746/78079616-bcf58e80-73ac-11ea-908e-408b9c700ea0.PNG)
![Numéro du jeu de bandes ACP](https://user-images.githubusercontent.com/44610746/78079622-c121ac00-73ac-11ea-9f8b-bac8868ab303.PNG)
![Numéro du jeu de bandes class signature](https://user-images.githubusercontent.com/44610746/78079632-c7178d00-73ac-11ea-9340-880016c609fe.PNG)
![Numéro du jeu de bandes Clustering](https://user-images.githubusercontent.com/44610746/78079645-cc74d780-73ac-11ea-8e51-88c1c65d2eb4.PNG)
![Spectral distance Numéro du jeu de bandes](https://user-images.githubusercontent.com/44610746/78079652-d1d22200-73ac-11ea-9031-f2149472fae9.PNG)

And for this one,  the non pop up text "Liste des bandes" should be replaced by " Liste des jeux de bandes" (List of band sets)
AND the pop up text should be: "Liste des numéros des jeux de bandes séparés par une virgule ,"
![Liste des numéros des jeux de bandes](https://user-images.githubusercontent.com/44610746/78079431-65efb980-73ac-11ea-8055-b00a0d52864b.PNG)

**Comment by semiautomaticgit** [comment]
I'm closing this because it was implemented, thank you
